version: '3'
services:
  web:
    build: .
    volumes:
     - ./web/cairo:/cairo
    ports:
     - "9000:9000"
    links:
     - app-db
    stdin_open: true
    command: play -Dhttps.protocols=TLSv1.2 -Dconfig.file=conf/dev-docker.conf run

  app-db:
    restart: always
    image: "postgres:9.1"
    volumes:
      - /var/lib/docker/volumes/bf244ebe6dba7909d19407018626e1693e73e685ce689c639a0b383bb4a77d70/_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 14FeDyAr
    ports:
     - '5432:5432'
