update lenguajeitem set lengi_texto = 'Account groups' where lengi_codigo = '1124' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Account groups' where lengi_codigo = '1125' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Default Account' where lengi_codigo = '1126' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Department' where lengi_codigo = '1127' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Departments' where lengi_codigo = '1128' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a company' where lengi_codigo = '1129' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Users' where lengi_codigo = '1130' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Department Father' where lengi_codigo = '1131' and leng_id = 3;
update lenguajeitem set lengi_texto = '(* This contains the department we are editing)' where lengi_codigo = '1132' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Departments' where lengi_codigo = '1133' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Company' where lengi_codigo = '1134' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a supplier or customer # 1 #' where lengi_codigo = '1135' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Department' where lengi_codigo = '1136' and leng_id = 3;
update lenguajeitem set lengi_texto = 'User' where lengi_codigo = '1137' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Do you want to propagate the users and roles permissions you have on the parent department to this department and its departments children? ;; This allows users with permissions on the top-level department extend such permits on the sub-departments. If ;; press if the permissions are propagated, pressing NO permissions are removed and you press CANCEL no changes are made to the permissions.' where lengi_codigo = '1138' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Physical Deposits' where lengi_codigo = '1139' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Physical Deposits' where lengi_codigo = '1140' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Physical Storage,' where lengi_codigo = '1141' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Physical Storage,' where lengi_codigo = '1142' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Dep Logic.' where lengi_codigo = '1143' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record the Logical Deposit' where lengi_codigo = '1144' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Computer Logic' where lengi_codigo = '1145' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Physical Storage,' where lengi_codigo = '1146' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Deposit Logic' where lengi_codigo = '1147' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Deposit Logic' where lengi_codigo = '1148' and leng_id = 3;
update lenguajeitem set lengi_texto = 'It''s temporary' where lengi_codigo = '1149' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Customer' where lengi_codigo = '1150' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Provider' where lengi_codigo = '1151' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record users;' where lengi_codigo = '1152' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a user # 1 #' where lengi_codigo = '1153' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Packaging' where lengi_codigo = '1154' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Packaging' where lengi_codigo = '1155' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must indicate an ability' where lengi_codigo = '1156' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a high' where lengi_codigo = '1157' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a width' where lengi_codigo = '1158' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a long' where lengi_codigo = '1159' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a tare' where lengi_codigo = '1160' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a unit' where lengi_codigo = '1161' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Packaging' where lengi_codigo = '1162' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Packaging' where lengi_codigo = '1163' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Capacity' where lengi_codigo = '1164' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Unity' where lengi_codigo = '1165' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Article stock' where lengi_codigo = '1166' and leng_id = 3;
update lenguajeitem set lengi_texto = 'High' where lengi_codigo = '1167' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Width' where lengi_codigo = '1168' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Largo' where lengi_codigo = '1169' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Company' where lengi_codigo = '1170' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Business' where lengi_codigo = '1171' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a company name' where lengi_codigo = '1172' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a CUIT' where lengi_codigo = '1173' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a tax category' where lengi_codigo = '1174' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Business' where lengi_codigo = '1175' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Bar Code' where lengi_codigo = '1177' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Company Name' where lengi_codigo = '1178' and leng_id = 3;
update lenguajeitem set lengi_texto = 'CUIT' where lengi_codigo = '1179' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Gross Income' where lengi_codigo = '1180' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tax Category' where lengi_codigo = '1181' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Final Consumer' where lengi_codigo = '1182' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Not Enrolled' where lengi_codigo = '1183' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enrolled' where lengi_codigo = '1184' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Alien' where lengi_codigo = '1185' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Exempt' where lengi_codigo = '1186' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Monotributo' where lengi_codigo = '1187' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Alien with Iva' where lengi_codigo = '1188' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Uncategorized' where lengi_codigo = '1189' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Not Responsible' where lengi_codigo = '1190' and leng_id = 3;
update lenguajeitem set lengi_texto = 'No responsible exempt' where lengi_codigo = '1191' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enrolled M' where lengi_codigo = '1192' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Check Order' where lengi_codigo = '1193' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Street' where lengi_codigo = '1194' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Street Number' where lengi_codigo = '1195' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Flat' where lengi_codigo = '1196' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Department.' where lengi_codigo = '1197' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Location' where lengi_codigo = '1198' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Zip,' where lengi_codigo = '1199' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fax' where lengi_codigo = '1200' and leng_id = 3;
update lenguajeitem set lengi_texto = 'An attempt to connect to the server has occurred ;; Technical description. # 1 #' where lengi_codigo = '1201' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Everything,' where lengi_codigo = '1202' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Date From' where lengi_codigo = '1203' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Up to Date' where lengi_codigo = '1204' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Documents Only' where lengi_codigo = '1205' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Scales' where lengi_codigo = '1206' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Scales' where lengi_codigo = '1207' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Scales' where lengi_codigo = '1208' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Feriado' where lengi_codigo = '1209' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Feriado' where lengi_codigo = '1210' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Remark.' where lengi_codigo = '1211' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Country' where lengi_codigo = '1212' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Local Feriado' where lengi_codigo = '1213' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Day' where lengi_codigo = '1214' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Month' where lengi_codigo = '1215' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Year' where lengi_codigo = '1216' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Recurring' where lengi_codigo = '1217' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Bank holiday' where lengi_codigo = '1218' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Labor Feriado' where lengi_codigo = '1219' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to save costs' where lengi_codigo = '1220' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Expenses' where lengi_codigo = '1221' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a type' where lengi_codigo = '1222' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Type' where lengi_codigo = '1223' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Air,' where lengi_codigo = '1224' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Maritime' where lengi_codigo = '1225' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fixed' where lengi_codigo = '1226' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Minimum' where lengi_codigo = '1227' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Amount' where lengi_codigo = '1228' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tax Rate' where lengi_codigo = '1229' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Expenditure' where lengi_codigo = '1230' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Expenditure' where lengi_codigo = '1231' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing language' where lengi_codigo = '1232' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Language,' where lengi_codigo = '1233' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Language,' where lengi_codigo = '1234' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Legends' where lengi_codigo = '1235' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Legends' where lengi_codigo = '1236' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a text for the legend,' where lengi_codigo = '1237' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Legend' where lengi_codigo = '1238' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Language,' where lengi_codigo = '1239' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Legend' where lengi_codigo = '1240' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Brand' where lengi_codigo = '1241' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Marks' where lengi_codigo = '1242' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Marks' where lengi_codigo = '1243' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Country' where lengi_codigo = '1244' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Countries' where lengi_codigo = '1245' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Country' where lengi_codigo = '1246' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Perception' where lengi_codigo = '1247' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Perceptions' where lengi_codigo = '1248' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a type of perception' where lengi_codigo = '1249' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a checkbook,' where lengi_codigo = '1250' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Perception' where lengi_codigo = '1251' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Perception' where lengi_codigo = '1252' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Perception type' where lengi_codigo = '1253' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Regime Sicore / Sifere' where lengi_codigo = '1254' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Minimum Amount' where lengi_codigo = '1255' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Checkbook' where lengi_codigo = '1256' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Import From' where lengi_codigo = '1257' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Mind Up' where lengi_codigo = '1258' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fixed Amount' where lengi_codigo = '1259' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an amount up # 1 #' where lengi_codigo = '1260' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify an account,' where lengi_codigo = '1261' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types of Perception' where lengi_codigo = '1262' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a Sicore code' where lengi_codigo = '1263' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types of Perception' where lengi_codigo = '1264' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sicore Code' where lengi_codigo = '1265' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Generate Sicore' where lengi_codigo = '1266' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Account' where lengi_codigo = '1267' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing PercepcionTipo' where lengi_codigo = '1268' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Person' where lengi_codigo = '1269' and leng_id = 3;
update lenguajeitem set lengi_texto = 'People,' where lengi_codigo = '1270' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please state the name,' where lengi_codigo = '1271' and leng_id = 3;
update lenguajeitem set lengi_texto = 'People,' where lengi_codigo = '1272' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Last Name' where lengi_codigo = '1273' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tel Work.' where lengi_codigo = '1274' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Internal' where lengi_codigo = '1275' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cell' where lengi_codigo = '1276' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tel house.' where lengi_codigo = '1277' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Department' where lengi_codigo = '1278' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cargo' where lengi_codigo = '1279' and leng_id = 3;
update lenguajeitem set lengi_texto = 'DOB.' where lengi_codigo = '1280' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Branch' where lengi_codigo = '1281' and leng_id = 3;
update lenguajeitem set lengi_texto = 'It has changed the name of shopping, you want to apply the same name to sales' where lengi_codigo = '1282' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Articles' where lengi_codigo = '1283' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a unit of purchase' where lengi_codigo = '1284' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a sales unit' where lengi_codigo = '1285' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a unit of stock,' where lengi_codigo = '1286' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate a relationship between the unit of purchase and sales unit' where lengi_codigo = '1287' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate a relationship between the unit and the unit sales of stock' where lengi_codigo = '1288' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a tax rate shopping for registered taxpayers,' where lengi_codigo = '1289' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a tax rate shopping for Responsible unregistered' where lengi_codigo = '1290' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please state sales tax rate to registered taxpayers' where lengi_codigo = '1291' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please state sales tax rate for Responsible unregistered' where lengi_codigo = '1292' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a name for sale,' where lengi_codigo = '1293' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate a relationship between the unit and the unit purchase stock' where lengi_codigo = '1294' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an account group for shopping' where lengi_codigo = '1295' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an account group for sales,' where lengi_codigo = '1296' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a checkbook to the identity of the Kit' where lengi_codigo = '1297' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Stock' where lengi_codigo = '1298' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Company' where lengi_codigo = '1299' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Export' where lengi_codigo = '1300' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Kit' where lengi_codigo = '1301' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Providers' where lengi_codigo = '1302' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Customers' where lengi_codigo = '1303' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Materials' where lengi_codigo = '1304' and leng_id = 3;
update lenguajeitem set lengi_texto = 'External Code' where lengi_codigo = '1305' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an item # 1 #' where lengi_codigo = '1364' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a quantity # 1 #' where lengi_codigo = '1365' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Inputs' where lengi_codigo = '1366' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Article' where lengi_codigo = '1367' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Formula default' where lengi_codigo = '1368' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item Series' where lengi_codigo = '1369' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item Lot,' where lengi_codigo = '1370' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Items' where lengi_codigo = '1371' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record items of kit' where lengi_codigo = '1372' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing alternate items of kit' where lengi_codigo = '1373' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Quantity' where lengi_codigo = '1374' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Variable' where lengi_codigo = '1375' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Alternative' where lengi_codigo = '1376' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Provider' where lengi_codigo = '1377' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing CAI' where lengi_codigo = '1378' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The current account credit can not exceed the total credit,' where lengi_codigo = '1380' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Shopping' where lengi_codigo = '1381' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Providers' where lengi_codigo = '1382' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a number of CAI # 1 #' where lengi_codigo = '1383' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify an expiration date # 1 #' where lengi_codigo = '1384' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a department # 1 #' where lengi_codigo = '1385' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Hold # 1 #' where lengi_codigo = '1386' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a group account # 1 #' where lengi_codigo = '1387' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an account # 1 #' where lengi_codigo = '1388' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing CAIs' where lengi_codigo = '1389' and leng_id = 3;
update lenguajeitem set lengi_texto = 'CAIS' where lengi_codigo = '1390' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Groups CTAS.' where lengi_codigo = '1391' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Credit' where lengi_codigo = '1392' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Withholding' where lengi_codigo = '1393' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Print Ticket' where lengi_codigo = '1394' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Payment Condition' where lengi_codigo = '1395' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cheque to order' where lengi_codigo = '1396' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Price List' where lengi_codigo = '1397' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sign Off' where lengi_codigo = '1398' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Credit cta.cte.' where lengi_codigo = '1399' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Total credit' where lengi_codigo = '1400' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Active Credit' where lengi_codigo = '1401' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Zone' where lengi_codigo = '1402' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hold' where lengi_codigo = '1403' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Group' where lengi_codigo = '1404' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Maturity' where lengi_codigo = '1405' and leng_id = 3;
update lenguajeitem set lengi_texto = 'No. CAI' where lengi_codigo = '1406' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Deductions' where lengi_codigo = '1407' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Departments' where lengi_codigo = '1408' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Provinces' where lengi_codigo = '1409' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Provinces' where lengi_codigo = '1410' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a country,' where lengi_codigo = '1411' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Provinces' where lengi_codigo = '1412' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing ReglaLiquidacion' where lengi_codigo = '1413' and leng_id = 3;
update lenguajeitem set lengi_texto = 'ReglaLiquidacion' where lengi_codigo = '1414' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Settlement Rules' where lengi_codigo = '1415' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Settlement Rules' where lengi_codigo = '1416' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record retention' where lengi_codigo = '1417' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a type of retention' where lengi_codigo = '1418' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hold' where lengi_codigo = '1419' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hold type' where lengi_codigo = '1420' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing RetencionTipo' where lengi_codigo = '1421' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types of Retention' where lengi_codigo = '1422' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types of Retention' where lengi_codigo = '1423' and leng_id = 3;
update lenguajeitem set lengi_texto = 'On VAT' where lengi_codigo = '1424' and leng_id = 3;
update lenguajeitem set lengi_texto = 'On Net' where lengi_codigo = '1425' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Profit' where lengi_codigo = '1426' and leng_id = 3;
update lenguajeitem set lengi_texto = 'On the Total' where lengi_codigo = '1427' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Beats' where lengi_codigo = '1428' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Beats' where lengi_codigo = '1429' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tables' where lengi_codigo = '1430' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 1' where lengi_codigo = '1431' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 1' where lengi_codigo = '1432' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 2' where lengi_codigo = '1433' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 2' where lengi_codigo = '1434' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 3' where lengi_codigo = '1435' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 3' where lengi_codigo = '1436' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 4' where lengi_codigo = '1437' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 4' where lengi_codigo = '1438' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 5' where lengi_codigo = '1439' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 5' where lengi_codigo = '1440' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 6' where lengi_codigo = '1441' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 6' where lengi_codigo = '1442' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 7' where lengi_codigo = '1443' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 7' where lengi_codigo = '1444' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 8' where lengi_codigo = '1445' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 8' where lengi_codigo = '1446' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 9' where lengi_codigo = '1447' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 9' where lengi_codigo = '1448' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table 10' where lengi_codigo = '1449' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item 10' where lengi_codigo = '1450' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing captions' where lengi_codigo = '1451' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The Tax ID is already used by the # 1 #' where lengi_codigo = '1452' and leng_id = 3;
update lenguajeitem set lengi_texto = 'C.U.I.T. Provider' where lengi_codigo = '1453' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table of items' where lengi_codigo = '1454' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tables of items' where lengi_codigo = '1455' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record items of tables of items' where lengi_codigo = '1456' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing RubroTabla' where lengi_codigo = '1457' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Branch' where lengi_codigo = '1458' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Branches' where lengi_codigo = '1459' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Branch' where lengi_codigo = '1460' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a number' where lengi_codigo = '1461' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing fees,' where lengi_codigo = '1462' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fee' where lengi_codigo = '1463' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Credit Card' where lengi_codigo = '1464' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Credit Cards' where lengi_codigo = '1465' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a bank account' where lengi_codigo = '1466' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an account for commissions' where lengi_codigo = '1467' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an account for coupons in wallet' where lengi_codigo = '1468' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify an account for the coupons presented,' where lengi_codigo = '1469' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an account for coupons rejected' where lengi_codigo = '1470' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a commission' where lengi_codigo = '1471' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Credit Card' where lengi_codigo = '1472' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fees' where lengi_codigo = '1473' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fees' where lengi_codigo = '1474' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Portfolio' where lengi_codigo = '1475' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Presented' where lengi_codigo = '1476' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Rejected' where lengi_codigo = '1477' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify the number of shares # 1 #' where lengi_codigo = '1478' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify the commission rate # 1 #' where lengi_codigo = '1479' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The percentage is outside the permitted range (0.00 to 200.00) # 1 #' where lengi_codigo = '1480' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Tax Rates' where lengi_codigo = '1481' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tax Rates' where lengi_codigo = '1482' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The percentage is outside the permitted range (0.00 to 200.00)' where lengi_codigo = '1483' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The percentage must be a number from 0.00 to 200.00,' where lengi_codigo = '1484' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Password: # 1 #' where lengi_codigo = '1541' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The Email Bug # 1 # - # 2 #' where lengi_codigo = '1542' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to save the holiday' where lengi_codigo = '1543' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Holidays' where lengi_codigo = '1544' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one day between 1 and 31' where lengi_codigo = '1545' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a month between 1 and 12' where lengi_codigo = '1546' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one day between 1 and 30' where lengi_codigo = '1547' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one day between 1 and 29' where lengi_codigo = '1548' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The date is not valid' where lengi_codigo = '1549' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Article indicating the serial number for this kit (# 1 #) between the items of the formula is not found;Do you want the system to add it for you.?' where lengi_codigo = '1550' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Article indicating the lot for this kit (# 1 #) between the items of the formula is not found;Do you want the system to add it for you.?' where lengi_codigo = '1551' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The document has not been saved' where lengi_codigo = '1552' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales Order' where lengi_codigo = '1553' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Before ordering info Order must save' where lengi_codigo = '1554' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This document can usually be edited' where lengi_codigo = '1555' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This only serves to modify documents stored and applied.' where lengi_codigo = '1556' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales Order' where lengi_codigo = '1557' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a date' where lengi_codigo = '1558' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a deposit' where lengi_codigo = '1559' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Branch' where lengi_codigo = '1560' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a payment' where lengi_codigo = '1561' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a Document' where lengi_codigo = '1562' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Customer' where lengi_codigo = '1563' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a delivery date' where lengi_codigo = '1564' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a retail product # 1 #' where lengi_codigo = '1565' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Additional' where lengi_codigo = '1566' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Document' where lengi_codigo = '1567' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State' where lengi_codigo = '1568' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Date' where lengi_codigo = '1569' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Delivery' where lengi_codigo = '1570' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Payment Cond.' where lengi_codigo = '1571' and leng_id = 3;
update lenguajeitem set lengi_texto = '2' where lengi_codigo = '1572' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Desc 1.' where lengi_codigo = '1573' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Deposit' where lengi_codigo = '1574' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Dossier' where lengi_codigo = '1575' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Branch Customer' where lengi_codigo = '1576' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Origin Province.' where lengi_codigo = '1577' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Province Destiny.' where lengi_codigo = '1578' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sub Total' where lengi_codigo = '1579' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Desc. 2' where lengi_codigo = '1580' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Net' where lengi_codigo = '1581' and leng_id = 3;
update lenguajeitem set lengi_texto = 'VAT RI' where lengi_codigo = '1582' and leng_id = 3;
update lenguajeitem set lengi_texto = 'VAT RNI' where lengi_codigo = '1583' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Total' where lengi_codigo = '1584' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Discount' where lengi_codigo = '1585' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Price' where lengi_codigo = '1586' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Price (LP)' where lengi_codigo = '1587' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Price c / Off.' where lengi_codigo = '1588' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales' where lengi_codigo = '1589' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales Order' where lengi_codigo = '1590' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to save the sales order,' where lengi_codigo = '1591' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Before you can sign the document you must save it.' where lengi_codigo = '1592' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The document has already been signed signature you want to delete' where lengi_codigo = '1593' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sign' where lengi_codigo = '1594' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must select a Document' where lengi_codigo = '1595' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Pending Stock' where lengi_codigo = '1596' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The product [# 1 #] has not defined its sales tax rate for VAT Registered Manager.' where lengi_codigo = '1597' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The product [# 1 #] has not defined its sales tax rate for the VAT charge not registered.' where lengi_codigo = '1598' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Application Sales Order' where lengi_codigo = '1600' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Budgets' where lengi_codigo = '1601' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Packing List' where lengi_codigo = '1602' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Delivery Notes / Invoices' where lengi_codigo = '1603' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Items1' where lengi_codigo = '1604' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Packing' where lengi_codigo = '1605' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Items2' where lengi_codigo = '1606' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Invoices' where lengi_codigo = '1607' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Applied' where lengi_codigo = '1608' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Pending' where lengi_codigo = '1609' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Proof,' where lengi_codigo = '1610' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Documents' where lengi_codigo = '1611' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Forward' where lengi_codigo = '1612' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Bill,' where lengi_codigo = '1613' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Customer Information' where lengi_codigo = '1614' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Add Note' where lengi_codigo = '1615' and leng_id = 3;
update lenguajeitem set lengi_texto = 'View Notes' where lengi_codigo = '1616' and leng_id = 3;
update lenguajeitem set lengi_texto = 'View Applications' where lengi_codigo = '1617' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Remark.' where lengi_codigo = '1618' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Product' where lengi_codigo = '1619' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must edit saved proof to see supporting documents' where lengi_codigo = '1620' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You. Has changed the document.;Want to use the already loaded in the form to the new voucher data?' where lengi_codigo = '1621' and leng_id = 3;
update lenguajeitem set lengi_texto = 'CrowSoft' where lengi_codigo = '1622' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You. Has changed the customer and the tax category of the previous client does not match the current customer.;;Do you want to keep the voucher number?' where lengi_codigo = '1623' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Bill of Sale' where lengi_codigo = '1624' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify an expiration date,' where lengi_codigo = '1625' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a quote' where lengi_codigo = '1626' and leng_id = 3;
update lenguajeitem set lengi_texto = 'In order to create the invoice must enlist the CUIT Customer.' where lengi_codigo = '1627' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Unable to obtain the CUIT Customer' where lengi_codigo = '1628' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The account associated with the customer and the account have different currencies Document.' where lengi_codigo = '1629' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Serial Number # 1 #' where lengi_codigo = '1630' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a price # 1 #' where lengi_codigo = '1631' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Lot # 1 #' where lengi_codigo = '1632' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a type Operation # 1 #' where lengi_codigo = '1633' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Mat.' where lengi_codigo = '1634' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Quote' where lengi_codigo = '1635' and leng_id = 3;
update lenguajeitem set lengi_texto = 'CAI' where lengi_codigo = '1636' and leng_id = 3;
update lenguajeitem set lengi_texto = 'I refer,' where lengi_codigo = '1637' and leng_id = 3;
update lenguajeitem set lengi_texto = 'VAT Date' where lengi_codigo = '1638' and leng_id = 3;
update lenguajeitem set lengi_texto = 'No. Series.' where lengi_codigo = '1639' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Lot' where lengi_codigo = '1640' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Bill of Sale' where lengi_codigo = '1641' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The product # 1 # has not defined its sales tax rate for VAT Registered Manager.' where lengi_codigo = '1642' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The product # 1 # has not defined its sales tax rate for the VAT charge not registered.' where lengi_codigo = '1643' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Maturity' where lengi_codigo = '1644' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record the financial year' where lengi_codigo = '1740' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Exercises Accounting' where lengi_codigo = '1741' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Accounting' where lengi_codigo = '1742' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Accounting Period' where lengi_codigo = '1743' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Opening' where lengi_codigo = '1744' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Closing Balance' where lengi_codigo = '1745' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Closing of Results' where lengi_codigo = '1746' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Generate Opening' where lengi_codigo = '1747' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Generate Closing Balance' where lengi_codigo = '1748' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Closing Generate Results' where lengi_codigo = '1749' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State the document to be used and the Customer that the invoice will be issued.' where lengi_codigo = '1655' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load selected only hours' where lengi_codigo = '1656' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select Project' where lengi_codigo = '1657' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Project' where lengi_codigo = '1658' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the hours I have indicated the amounts billed each of them.' where lengi_codigo = '1659' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hours' where lengi_codigo = '1660' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Type of transaction' where lengi_codigo = '1661' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Apply' where lengi_codigo = '1662' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Complete the following data Invoice' where lengi_codigo = '1663' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Discount 1' where lengi_codigo = '1664' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Do you want to cancel?' where lengi_codigo = '1665' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more projects.' where lengi_codigo = '1666' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a price for the item # 1 #.' where lengi_codigo = '1667' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more hours.' where lengi_codigo = '1668' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate the date of the invoice' where lengi_codigo = '1669' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Packing Lists,' where lengi_codigo = '1670' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the Packing List for this Customer.' where lengi_codigo = '1671' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items of the Packing List for this Customer.' where lengi_codigo = '1672' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate invoices on Packing List,' where lengi_codigo = '1673' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load only selected Packing List' where lengi_codigo = '1674' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the Packing List' where lengi_codigo = '1675' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the items I have indicated the amounts billed each' where lengi_codigo = '1676' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more Delivery Notes.' where lengi_codigo = '1677' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more items.' where lengi_codigo = '1678' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the Delivery Notes for this Client' where lengi_codigo = '1679' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items in the Delivery Notes for this Client' where lengi_codigo = '1680' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate invoices on Delivery Notes.' where lengi_codigo = '1681' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load only selected Delivery Notes' where lengi_codigo = '1682' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the Delivery Notes' where lengi_codigo = '1683' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the orders for this customer' where lengi_codigo = '1684' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items of orders for this customer' where lengi_codigo = '1685' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate invoices on orders.' where lengi_codigo = '1686' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load only selected orders' where lengi_codigo = '1687' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select Order' where lengi_codigo = '1688' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more orders.' where lengi_codigo = '1689' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Charge' where lengi_codigo = '1690' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Associated Document' where lengi_codigo = '1691' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Ledger Transaction' where lengi_codigo = '1692' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This proof does not have a valid associated stock.' where lengi_codigo = '1693' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Orders' where lengi_codigo = '1694' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the budget for this Client' where lengi_codigo = '1695' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items of the budget for this Client' where lengi_codigo = '1696' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Welcome to Sales Order Wizard,' where lengi_codigo = '1697' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate orders on Budgets.' where lengi_codigo = '1698' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State the document to be used and the Customer that will be issued the Order' where lengi_codigo = '1699' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load only selected Budgets' where lengi_codigo = '1700' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the Budget' where lengi_codigo = '1701' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the items I stating the quantities to be sent to each of them.' where lengi_codigo = '1702' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Complete the following Order,' where lengi_codigo = '1703' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more budgets.' where lengi_codigo = '1704' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate the date of the Order,' where lengi_codigo = '1705' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Budget for Sale,' where lengi_codigo = '1706' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record the sales budget' where lengi_codigo = '1707' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Estimates of Sale' where lengi_codigo = '1708' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Estimates of Sale' where lengi_codigo = '1709' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Create Order' where lengi_codigo = '1710' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Budget # 1 #' where lengi_codigo = '1711' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales Delivery Notes' where lengi_codigo = '1712' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Stock Transfer' where lengi_codigo = '1713' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Consumption' where lengi_codigo = '1714' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Temporary consumption' where lengi_codigo = '1715' and leng_id = 3;
update lenguajeitem set lengi_texto = 'View production' where lengi_codigo = '1716' and leng_id = 3;
update lenguajeitem set lengi_texto = 'View All' where lengi_codigo = '1717' and leng_id = 3;
update lenguajeitem set lengi_texto = 'I refer sales' where lengi_codigo = '1718' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales Delivery Notes' where lengi_codigo = '1719' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Orders / Orders' where lengi_codigo = '1720' and leng_id = 3;
update lenguajeitem set lengi_texto = 'I refer to Sell Application' where lengi_codigo = '1721' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Delivery Notes' where lengi_codigo = '1722' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the inputs for the selected items,' where lengi_codigo = '1723' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Welcome to Assistant Sales Delivery Notes' where lengi_codigo = '1724' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate Ordering Delivery Notes.' where lengi_codigo = '1725' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State the document to be used and the Customer will be issued to the packing slip.' where lengi_codigo = '1726' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Temporary Storage' where lengi_codigo = '1727' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter the quantities of inputs for each item that you send.' where lengi_codigo = '1728' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Input' where lengi_codigo = '1729' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Input Temp.' where lengi_codigo = '1730' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Amount Aux.' where lengi_codigo = '1731' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Complete the following details I refer,' where lengi_codigo = '1732' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate the date I refer.' where lengi_codigo = '1733' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the orders for this customer' where lengi_codigo = '1734' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items of the orders for this customer' where lengi_codigo = '1735' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate the Delivery Notes on orders.' where lengi_codigo = '1736' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load only selected orders' where lengi_codigo = '1737' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select Orders' where lengi_codigo = '1738' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more orders.' where lengi_codigo = '1739' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record repair steps' where lengi_codigo = '1750' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Steps to Repair' where lengi_codigo = '1751' and leng_id = 3;
update lenguajeitem set lengi_texto = '. Do not enter Enter as surrender their few hours working hours per day :)' where lengi_codigo = '1752' and leng_id = 3;
update lenguajeitem set lengi_texto = 'C. Payment' where lengi_codigo = '1835' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cotiz.' where lengi_codigo = '1650' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Even though it will not try to get your people to work much, at least not on planet earth :).' where lengi_codigo = '1753' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Steps to Repair' where lengi_codigo = '1754' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Services' where lengi_codigo = '1755' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Weekly' where lengi_codigo = '1756' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Monthly' where lengi_codigo = '1757' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Special Dates' where lengi_codigo = '1758' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hours x Day (base 60 minutes eg: 09:30 = 9.3)' where lengi_codigo = '1760' and leng_id = 3;
update lenguajeitem set lengi_texto = 'All times type' where lengi_codigo = '1759' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Branch / Department' where lengi_codigo = '1761' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Project / Contract' where lengi_codigo = '1762' and leng_id = 3;
update lenguajeitem set lengi_texto = 'All repair steps go through five states identified;by green, yellow, orange, red and gray colors as;They approach their date / time term.;;Green is the initial state, the yellow and orange occur when;lack X minutes / hours / days to complete the task associated with re repair step.;Red is when the task is due and has not been finalized.;Gray is for tasks that have been completed.' where lengi_codigo = '1763' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing AlarmaItem' where lengi_codigo = '1764' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Special Dates' where lengi_codigo = '1765' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to save the day' where lengi_codigo = '1766' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Time From' where lengi_codigo = '1767' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Time Up' where lengi_codigo = '1768' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Time,' where lengi_codigo = '1769' and leng_id = 3;
update lenguajeitem set lengi_texto = 'From the Top,' where lengi_codigo = '1770' and leng_id = 3;
update lenguajeitem set lengi_texto = 'From the previous step,' where lengi_codigo = '1771' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Time From' where lengi_codigo = '1772' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Workdays' where lengi_codigo = '1773' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Calendar days' where lengi_codigo = '1774' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Work' where lengi_codigo = '1775' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sequence' where lengi_codigo = '1776' and leng_id = 3;
update lenguajeitem set lengi_texto = 'I refer Required' where lengi_codigo = '1777' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Mandatory Invoice' where lengi_codigo = '1778' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Alarm 1' where lengi_codigo = '1779' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Minutes,' where lengi_codigo = '1780' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Alarm 2' where lengi_codigo = '1781' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Email Home' where lengi_codigo = '1782' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Email Alarm 1' where lengi_codigo = '1783' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Email Alarm 2' where lengi_codigo = '1784' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Email Overcome' where lengi_codigo = '1785' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Steps to Repair Type' where lengi_codigo = '1786' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a date # 1 #' where lengi_codigo = '1787' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a name for the item # 1 #' where lengi_codigo = '1788' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an order for item # 1 #' where lengi_codigo = '1789' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a type of repair step for item # 1 #' where lengi_codigo = '1790' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing type repair steps' where lengi_codigo = '1791' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types of repair steps' where lengi_codigo = '1792' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types of Alarms' where lengi_codigo = '1793' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error while writing parameters.' where lengi_codigo = '1794' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tasks' where lengi_codigo = '1795' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Repair Parts 1 #' where lengi_codigo = '1796' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The teams must enter the system travez Service Order or Purchase Delivery Notes.' where lengi_codigo = '1797' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record the serial number of the product.' where lengi_codigo = '1798' and leng_id = 3;
update lenguajeitem set lengi_texto = 'ProductoNroSeries' where lengi_codigo = '1799' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Computers' where lengi_codigo = '1800' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Team' where lengi_codigo = '1801' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Maturity date.' where lengi_codigo = '1802' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing EquipoDetalle' where lengi_codigo = '1803' and leng_id = 3;
update lenguajeitem set lengi_texto = 'EquipoDetalles' where lengi_codigo = '1804' and leng_id = 3;
update lenguajeitem set lengi_texto = 'EquipoDetalle' where lengi_codigo = '1805' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a category' where lengi_codigo = '1806' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Details of equipment' where lengi_codigo = '1807' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Extreme Team' where lengi_codigo = '1808' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Order' where lengi_codigo = '1809' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table' where lengi_codigo = '1810' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a Name # 1 #' where lengi_codigo = '1811' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an order # 1 #' where lengi_codigo = '1812' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a type # 1 #' where lengi_codigo = '1813' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a table # 1 #' where lengi_codigo = '1814' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an SQL statement # 1 #' where lengi_codigo = '1815' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a separate list" | "or a sentence sql # 1 #' where lengi_codigo = '1816' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Parameters' where lengi_codigo = '1817' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing task' where lengi_codigo = '1818' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Filter by date' where lengi_codigo = '1819' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Serial Number' where lengi_codigo = '1820' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Only in the Enterprise' where lengi_codigo = '1821' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Responsible' where lengi_codigo = '1822' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Unallocated' where lengi_codigo = '1823' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Assigned by' where lengi_codigo = '1824' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Priority' where lengi_codigo = '1825' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Equipment # 1 #' where lengi_codigo = '1826' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing type Falla' where lengi_codigo = '1827' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fault Types' where lengi_codigo = '1828' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fault Types' where lengi_codigo = '1829' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Service Orders' where lengi_codigo = '1830' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing service orders' where lengi_codigo = '1831' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Time,' where lengi_codigo = '1832' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Branch / Dept.' where lengi_codigo = '1833' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Draft/Contract' where lengi_codigo = '1834' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Task' where lengi_codigo = '1836' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fault' where lengi_codigo = '1837' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Service Orders' where lengi_codigo = '1838' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record Service Order,' where lengi_codigo = '1839' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This team:;;#1#;Ns: # 2 #;-Ns2: # 3 #;-Ns3: # 4 #;;Whether it is in the company''s warehouse:;;#5#' where lengi_codigo = '1840' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This team:;;#1#;Ns: # 2 #;-Ns2: # 3 #;-Ns3: # 4 #;;It is a re-entry and is mentioned in the Service Order # # 5 # 6 #;;Are you sure re-entry team?' where lengi_codigo = '1841' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Service Order # 1 #' where lengi_codigo = '1842' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Part of repair' where lengi_codigo = '1843' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The Budget Repair Parts stock type not move.' where lengi_codigo = '1844' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This document has no associated auxiliary document.' where lengi_codigo = '1845' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Technical' where lengi_codigo = '1846' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Budget' where lengi_codigo = '1847' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Repair' where lengi_codigo = '1848' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Approved' where lengi_codigo = '1849' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Part of repair' where lengi_codigo = '1850' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Services' where lengi_codigo = '1851' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must record the calculation to print.' where lengi_codigo = '1852' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Print,' where lengi_codigo = '1853' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a document number' where lengi_codigo = '1854' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a title.' where lengi_codigo = '1855' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a path' where lengi_codigo = '1856' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an Invoice' where lengi_codigo = '1857' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please state the change' where lengi_codigo = '1858' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a foreign currency' where lengi_codigo = '1859' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Provider' where lengi_codigo = '1860' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Observations' where lengi_codigo = '1861' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Provisional' where lengi_codigo = '1862' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Definitive' where lengi_codigo = '1863' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Title' where lengi_codigo = '1864' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Road' where lengi_codigo = '1865' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Invoice' where lengi_codigo = '1866' and leng_id = 3;
update lenguajeitem set lengi_texto = 'M. COMEX' where lengi_codigo = '1867' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Change 1' where lengi_codigo = '1868' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Change 2' where lengi_codigo = '1869' and leng_id = 3;
update lenguajeitem set lengi_texto = 'M. Origin' where lengi_codigo = '1870' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Pass,' where lengi_codigo = '1871' and leng_id = 3;
update lenguajeitem set lengi_texto = 'T. Expenses' where lengi_codigo = '1872' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Boarding' where lengi_codigo = '1873' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Porc FOB.' where lengi_codigo = '1874' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Changes' where lengi_codigo = '1875' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Porc FOB Final.' where lengi_codigo = '1876' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Concept' where lengi_codigo = '1877' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Porc ./$' where lengi_codigo = '1878' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Shopping' where lengi_codigo = '1879' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Import Cost Ratio' where lengi_codigo = '1880' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Want to recalculate the amounts for rights and statistics?' where lengi_codigo = '1881' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You want to recalculate the amount of VAT 21%' where lengi_codigo = '1882' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You want to recalculate the amount of VAT 3431/91' where lengi_codigo = '1883' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You want to recalculate the amount for 3543/92 Earnings' where lengi_codigo = '1884' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Coefficient' where lengi_codigo = '1885' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enterprise Way' where lengi_codigo = '1886' and leng_id = 3;
update lenguajeitem set lengi_texto = 'View Provider Info' where lengi_codigo = '1887' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Calculation Import Dispatch # 1 #' where lengi_codigo = '1888' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Invoice' where lengi_codigo = '1889' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Seat' where lengi_codigo = '1890' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Stock Transfer' where lengi_codigo = '1891' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Invoices' where lengi_codigo = '1892' and leng_id = 3;
update lenguajeitem set lengi_texto = 'In order to create the Bill must enlist the CUIT Provider.' where lengi_codigo = '1893' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Unable to obtain the CUIT Provider' where lengi_codigo = '1894' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The account associated with the provider and the account of the document have different currencies.' where lengi_codigo = '1895' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a file # 1 #' where lengi_codigo = '1896' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an amount # 1 #' where lengi_codigo = '1897' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an amount on the debit or Credited # 1 #' where lengi_codigo = '1898' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a product of Purchase # 1 #' where lengi_codigo = '1899' and leng_id = 3;
update lenguajeitem set lengi_texto = 'F. VAT' where lengi_codigo = '1900' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Origin' where lengi_codigo = '1901' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Destination' where lengi_codigo = '1902' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Proof Type' where lengi_codigo = '1903' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please,' where lengi_codigo = '1904' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Being' where lengi_codigo = '1905' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Invoices' where lengi_codigo = '1906' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Purchase Invoice' where lengi_codigo = '1907' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Application Purchase Invoice' where lengi_codigo = '1908' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Amount Invoiced' where lengi_codigo = '1909' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record Payment Order' where lengi_codigo = '1910' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the Delivery Notes for Quotation' where lengi_codigo = '1911' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items in the Delivery Notes for Quotation' where lengi_codigo = '1912' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Welcome to the Assistant Purchase Invoices' where lengi_codigo = '1913' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State the document to be used and the supplier that the invoice will be issued,' where lengi_codigo = '1914' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Perceptions Indicate if appropriate.' where lengi_codigo = '1915' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the Purchase Orders for Quotation' where lengi_codigo = '1916' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Could not load the items of purchase orders for this supplier' where lengi_codigo = '1917' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate invoices on purchase orders.' where lengi_codigo = '1918' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Load only selected Purchase Orders' where lengi_codigo = '1919' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select the Purchase Orders,' where lengi_codigo = '1920' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter one or more orders.' where lengi_codigo = '1921' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Payment Order' where lengi_codigo = '1922' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Invoice # 1 #' where lengi_codigo = '1923' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order' where lengi_codigo = '1924' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record Purchase Order' where lengi_codigo = '1925' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order' where lengi_codigo = '1926' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order Application' where lengi_codigo = '1927' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Purchase Order # 1 #' where lengi_codigo = '1928' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Welcome to the Assistant Purchase Orders' where lengi_codigo = '1929' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate Purchase Orders Ordering.' where lengi_codigo = '1930' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State the document to be used and the supplier who will issue the Purchase Order' where lengi_codigo = '1931' and leng_id = 3;
update lenguajeitem set lengi_texto = 'No.' where lengi_codigo = '1932' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Complete the following information to the Purchase Order,' where lengi_codigo = '1933' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Must indicate the date of the Purchase Order,' where lengi_codigo = '1934' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order' where lengi_codigo = '1935' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing the Purchase Order' where lengi_codigo = '1936' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order' where lengi_codigo = '1937' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a User' where lengi_codigo = '1938' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order' where lengi_codigo = '1939' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Order Application' where lengi_codigo = '1940' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Quotes / Purchase Orders' where lengi_codigo = '1941' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Create Purchase Order' where lengi_codigo = '1942' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Orders # 1 #' where lengi_codigo = '1943' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Delivery Notes' where lengi_codigo = '1944' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error while writing Purchase Delivery Notes' where lengi_codigo = '1945' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Calculating Coefficient.' where lengi_codigo = '1946' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Purchase Delivery Notes' where lengi_codigo = '1947' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing I refer to Purchase' where lengi_codigo = '1948' and leng_id = 3;
update lenguajeitem set lengi_texto = 'I refer Purchase Application' where lengi_codigo = '1949' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Orders' where lengi_codigo = '1950' and leng_id = 3;
update lenguajeitem set lengi_texto = 'I refer Notes # 1 #' where lengi_codigo = '1951' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Welcome to the Assistant Purchase Delivery Notes' where lengi_codigo = '1952' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can generate the Delivery Notes on Purchase Orders.' where lengi_codigo = '1953' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State the document to be used and the Supplier to which I refer is the issue.' where lengi_codigo = '1954' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Ledger Transaction' where lengi_codigo = '1955' and leng_id = 3;
update lenguajeitem set lengi_texto = 'There is a document associated with doct_id # 1 #;;Contact CrowSoft support for technical assistance.' where lengi_codigo = '1956' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The debit and credit must match for the swing seat.' where lengi_codigo = '1957' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please state the amount in the account currency # 1 #' where lengi_codigo = '1958' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an amount on the debit or in credit, not both columns # 1 #' where lengi_codigo = '1959' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Generated' where lengi_codigo = '1960' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Total should' where lengi_codigo = '1961' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Total Haber' where lengi_codigo = '1962' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Currency Origin' where lengi_codigo = '1963' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Ledger Transaction' where lengi_codigo = '1964' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record the Ledger Transaction' where lengi_codigo = '1965' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on seat # 1 #' where lengi_codigo = '1966' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Renumber Seats' where lengi_codigo = '1967' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a type of summary for Shopping.' where lengi_codigo = '1968' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a type of summary for Sales.' where lengi_codigo = '1969' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Renumber seat' where lengi_codigo = '1970' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Exercise' where lengi_codigo = '1971' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Type summary Purchases' where lengi_codigo = '1972' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sales Summary type' where lengi_codigo = '1973' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an accounting circuit' where lengi_codigo = '1974' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify a start date for the exercise' where lengi_codigo = '1975' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify an end date for the exercise' where lengi_codigo = '1976' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Document must indicate a seat' where lengi_codigo = '1977' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The previous year is not closed,' where lengi_codigo = '1978' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The exercise is not open' where lengi_codigo = '1979' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The last year has closed Results' where lengi_codigo = '1980' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Charge for Range,' where lengi_codigo = '1981' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Paste from Excel' where lengi_codigo = '1982' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Delete' where lengi_codigo = '1983' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Alt.' where lengi_codigo = '1984' and leng_id = 3;
update lenguajeitem set lengi_texto = 'To upload range numbers must be placed in the number column to edit.' where lengi_codigo = '1985' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This option is not yet implemented' where lengi_codigo = '1986' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The number-edit article did not find.' where lengi_codigo = '1987' and leng_id = 3;
update lenguajeitem set lengi_texto = 'In order to paste numbers from MS Excel must be placed in the number column to edit.' where lengi_codigo = '1988' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Saving ...' where lengi_codigo = '1989' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Closing ...' where lengi_codigo = '1990' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Item Kit' where lengi_codigo = '1991' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Series' where lengi_codigo = '1992' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Parts Production Kit' where lengi_codigo = '1993' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Check Both' where lengi_codigo = '1994' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Part Production Kit' where lengi_codigo = '1995' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a product Stock # 1 #' where lengi_codigo = '1996' and leng_id = 3;
update lenguajeitem set lengi_texto = 'No. Serial / Lot / Alt..' where lengi_codigo = '1997' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Stock' where lengi_codigo = '1998' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Part of Production Kit' where lengi_codigo = '1999' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Part of Production Kit' where lengi_codigo = '2000' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record the Part Of Kit' where lengi_codigo = '2001' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You want to run this process?' where lengi_codigo = '2002' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Are you really sure?' where lengi_codigo = '2003' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes on Part Prod Kit # 1 #.' where lengi_codigo = '2004' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You want to see the consumer?' where lengi_codigo = '2005' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Want to see what occurred?' where lengi_codigo = '2006' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Counts Stock' where lengi_codigo = '2007' and leng_id = 3;
update lenguajeitem set lengi_texto = 'View expenses' where lengi_codigo = '2008' and leng_id = 3;
update lenguajeitem set lengi_texto = 'See Income' where lengi_codigo = '2009' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes Stock Count # 1 #' where lengi_codigo = '2010' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Source' where lengi_codigo = '2011' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Destination' where lengi_codigo = '2012' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The Origin and Destiny deposit can not be equal' where lengi_codigo = '2013' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Warehouse Source' where lengi_codigo = '2014' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Deposit Destiny' where lengi_codigo = '2015' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Stock Transfer' where lengi_codigo = '2016' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Agendas' where lengi_codigo = '2633' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Agendas' where lengi_codigo = '2634' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must select an Agenda' where lengi_codigo = '2635' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Contacts' where lengi_codigo = '2636' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an Agenda' where lengi_codigo = '2637' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Agenda' where lengi_codigo = '2638' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You do not have permission to edit this contact,' where lengi_codigo = '2639' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Contact,' where lengi_codigo = '2640' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to record Contact' where lengi_codigo = '2641' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must indicate that you want to edit Agenda' where lengi_codigo = '2642' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a project' where lengi_codigo = '2643' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Sub-Project' where lengi_codigo = '2644' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Target,' where lengi_codigo = '2645' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The Hours should be in the range 0-23,' where lengi_codigo = '2646' and leng_id = 3;
update lenguajeitem set lengi_texto = 'The minutes should be in the range 0-59,' where lengi_codigo = '2647' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Please specify the time used' where lengi_codigo = '2648' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You do not have permission to add or modify hours of this project.' where lengi_codigo = '2649' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hours' where lengi_codigo = '2650' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Objective' where lengi_codigo = '2651' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sub-Project' where lengi_codigo = '2652' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Billable' where lengi_codigo = '2653' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to save time' where lengi_codigo = '2654' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error loading navigation parameters of Time' where lengi_codigo = '2655' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Failed to save the parameters of Time Navigation' where lengi_codigo = '2656' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Project Item' where lengi_codigo = '2657' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Notes Hours # 1 #' where lengi_codigo = '2658' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Priorities' where lengi_codigo = '2659' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Priority' where lengi_codigo = '2660' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing Priority' where lengi_codigo = '2661' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Project / Groups / Contracts' where lengi_codigo = '2662' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a State # 1 #' where lengi_codigo = '2663' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sub Project' where lengi_codigo = '2664' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Objectives' where lengi_codigo = '2665' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Prices' where lengi_codigo = '2666' and leng_id = 3;
update lenguajeitem set lengi_texto = 'States' where lengi_codigo = '2667' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Require Approval' where lengi_codigo = '2668' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Effective' where lengi_codigo = '2669' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Valid until' where lengi_codigo = '2670' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Parent Project' where lengi_codigo = '2671' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Maximum Size in Attachment' where lengi_codigo = '2672' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fees' where lengi_codigo = '2673' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must specify a completion date' where lengi_codigo = '2674' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You do not have permission to add or edit tasks for this project.' where lengi_codigo = '2675' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Services' where lengi_codigo = '2676' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sub tasks' where lengi_codigo = '2677' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Main task' where lengi_codigo = '2678' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Approved' where lengi_codigo = '2679' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Finished' where lengi_codigo = '2680' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Rejected' where lengi_codigo = '2681' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Order of Service' where lengi_codigo = '2682' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Product / Equipment' where lengi_codigo = '2683' and leng_id = 3;
update lenguajeitem set lengi_texto = 'No. Series / Inventory.' where lengi_codigo = '2684' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tasks' where lengi_codigo = '2685' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Task Templates' where lengi_codigo = '2686' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Requirements / Tasks' where lengi_codigo = '2687' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Task status' where lengi_codigo = '2688' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State tasks' where lengi_codigo = '2689' and leng_id = 3;
update lenguajeitem set lengi_texto = 'State tasks' where lengi_codigo = '2690' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error writing job status' where lengi_codigo = '2691' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Finished' where lengi_codigo = '2692' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Rejected' where lengi_codigo = '2693' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Fulfilled' where lengi_codigo = '2694' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error loading navigation parameters Task' where lengi_codigo = '2695' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Error while writing parameters Task navigation' where lengi_codigo = '2696' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter the module name' where lengi_codigo = '2697' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Reports' where lengi_codigo = '2698' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a Stored Procedure' where lengi_codigo = '2699' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Enter a Module' where lengi_codigo = '2700' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a default presentation' where lengi_codigo = '2701' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter an Owner,' where lengi_codigo = '2702' and leng_id = 3;
update lenguajeitem set lengi_texto = 'System' where lengi_codigo = '2703' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Reports' where lengi_codigo = '2704' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Validate Reports and CSR' where lengi_codigo = '2705' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sumaries' where lengi_codigo = '2706' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Stored Procedure' where lengi_codigo = '2707' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Report' where lengi_codigo = '2708' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Module' where lengi_codigo = '2709' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Default display' where lengi_codigo = '2710' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Grid' where lengi_codigo = '2711' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Graphics' where lengi_codigo = '2712' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Process' where lengi_codigo = '2713' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cairo Development' where lengi_codigo = '2714' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cairo Implementation' where lengi_codigo = '2715' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Third Development' where lengi_codigo = '2716' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Third Implementation' where lengi_codigo = '2717' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Owner' where lengi_codigo = '2718' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Total Grales.' where lengi_codigo = '2719' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Hidden columns' where lengi_codigo = '2720' and leng_id = 3;
update lenguajeitem set lengi_texto = 'String Connection' where lengi_codigo = '2721' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Pillar box' where lengi_codigo = '2722' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Visible,' where lengi_codigo = '2723' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a column # 1 #' where lengi_codigo = '2724' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Default' where lengi_codigo = '2725' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Column' where lengi_codigo = '2726' and leng_id = 3;
update lenguajeitem set lengi_texto = 'URL' where lengi_codigo = '2727' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a URL # 1 #' where lengi_codigo = '2728' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a Transaction # 1 #' where lengi_codigo = '2729' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Configuration Reports' where lengi_codigo = '2730' and leng_id = 3;
update lenguajeitem set lengi_texto = 'You must enter a company to associate the logos' where lengi_codigo = '2731' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Setting' where lengi_codigo = '2732' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Configuration Reports' where lengi_codigo = '2733' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Logos,' where lengi_codigo = '2734' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Folder Report' where lengi_codigo = '2735' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Time Out Connection' where lengi_codigo = '2736' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Command Time Out' where lengi_codigo = '2737' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Logo Chico' where lengi_codigo = '2738' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Big Logo' where lengi_codigo = '2739' and leng_id = 3;
update lenguajeitem set lengi_texto = 'There are no reports defined in Cairo,' where lengi_codigo = '2740' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sure you want to abort the process' where lengi_codigo = '2741' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Reports whose definition matches the CSR' where lengi_codigo = '2742' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Total' where lengi_codigo = '2743' and leng_id = 3;
update lenguajeitem set lengi_texto = 'There is no link associated with this document.;;This may be because the link is showing opening balances.' where lengi_codigo = '2744' and leng_id = 3;
update lenguajeitem set lengi_texto = 'This report has no presentation in Preview or printer.It can only be displayed in a grid view.' where lengi_codigo = '2745' and leng_id = 3;
update lenguajeitem set lengi_texto = 'There is no information to display for this report.' where lengi_codigo = '2746' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Defining the Report' where lengi_codigo = '2747' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Welcome to New Reports Wizard,' where lengi_codigo = '2748' and leng_id = 3;
update lenguajeitem set lengi_texto = 'With this wizard you can add new reports based on reports from Cairo on who has access.' where lengi_codigo = '2749' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Select Report' where lengi_codigo = '2750' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Specify parameters that are editable in this Report,' where lengi_codigo = '2751' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Value' where lengi_codigo = '2752' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Editable' where lengi_codigo = '2753' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Save Report' where lengi_codigo = '2754' and leng_id = 3;