update lenguajeitem set lengi_texto = 'Help & Settings articles' where lengi_codigo = '3910' and leng_id = 3;
update lenguajeitem set lengi_texto = '& B.O.M.' where lengi_codigo = '5135' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Tariff' where lengi_codigo = '5041' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Students' where lengi_codigo = '4681' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Wages' where lengi_codigo = '3973' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Response Template' where lengi_codigo = '5000' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Formulas & Settlement' where lengi_codigo = '4565' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Catalogues Web' where lengi_codigo = '3563' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Printer Setup' where lengi_codigo = '3548' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Partners' where lengi_codigo = '3690' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Open / Close Banks' where lengi_codigo = '4725' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Community & Internet' where lengi_codigo = '5025' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Partner' where lengi_codigo = '3694' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Seats Accounting & Import' where lengi_codigo = '3938' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Internet community' where lengi_codigo = '5030' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Materials' where lengi_codigo = '4666' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Articles' where lengi_codigo = '5071' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Marking & Ironing Prices' where lengi_codigo = '3507' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Shares' where lengi_codigo = '3701' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Orders & Import Services' where lengi_codigo = '5054' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Document Types' where lengi_codigo = '4673' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Checking in & Sales Stock Exchange' where lengi_codigo = '3703' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Settlement & Templates' where lengi_codigo = '4551' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Ca & ja' where lengi_codigo = '3498' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Classrooms' where lengi_codigo = '4670' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Internet Community' where lengi_codigo = '4999' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Tariff & Positions' where lengi_codigo = '4970' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Dispatch & Lists' where lengi_codigo = '4862' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Presentism and Assistance' where lengi_codigo = '4583' and leng_id = 3;
update lenguajeitem set lengi_texto = 'C & RADE Abroad' where lengi_codigo = '5134' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Educational Institutes &' where lengi_codigo = '4690' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Production & Order Kit' where lengi_codigo = '3723' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Categories Catalogs & Web' where lengi_codigo = '4592' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Profession / Specialty' where lengi_codigo = '4520' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Configuration & Price Schedule' where lengi_codigo = '4617' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Navigate Internet Community' where lengi_codigo = '5035' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Types of Assistance' where lengi_codigo = '4589' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Pricing & Sales' where lengi_codigo = '4900' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Streets' where lengi_codigo = '3923' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Roadmaps' where lengi_codigo = '3747' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Questions' where lengi_codigo = '5096' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Union' where lengi_codigo = '3971' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sale Shares Soc Protector' where lengi_codigo = '3712' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Educational Institutes' where lengi_codigo = '4667' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Import Embargo Padron table' where lengi_codigo = '4916' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Overdue & CAIS List' where lengi_codigo = '5136' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Insurance' where lengi_codigo = '4529' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Guarantees on Bank Loans &' where lengi_codigo = '3702' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Payment' where lengi_codigo = '5061' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Cash & Collections' where lengi_codigo = '5111' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Employees' where lengi_codigo = '4524' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Groups & Files' where lengi_codigo = '3782' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Registration Forms Line & Partners' where lengi_codigo = '3691' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Types & Settlement Code' where lengi_codigo = '4843' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Guarantees' where lengi_codigo = '3700' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Sale Shares Participate Soc.' where lengi_codigo = '3714' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Surrender' where lengi_codigo = '5137' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Personnel Management' where lengi_codigo = '3972' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Courses' where lengi_codigo = '4693' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Guarantees Bank Lending with Free Vto.' where lengi_codigo = '3708' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Teachers' where lengi_codigo = '4677' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Convention Association' where lengi_codigo = '4508' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Personal &' where lengi_codigo = '4582' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Texts' where lengi_codigo = '5014' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Inflation Adjustment Schemes' where lengi_codigo = '3611' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Table Import & Perc / Ret IIBB BS AS..' where lengi_codigo = '3729' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Settlement Assets' where lengi_codigo = '4610' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Indices Inflation Adjustment' where lengi_codigo = '3625' and leng_id = 3;
update lenguajeitem set lengi_texto = 'Modes & Sale' where lengi_codigo = '5076' and leng_id = 3;
update lenguajeitem set lengi_texto = '& Types of Contact' where lengi_codigo = '4658' and leng_id = 3;
update lenguajeitem set lengi_texto = '& E-Mails' where lengi_codigo = '5024' and leng_id = 3;