

update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 689;
update sysmenu set me_action = '', me_action2 = '' where me_id = 692;
update sysmenu set me_action = '', me_action2 = '' where me_id = 825;
update sysmenu set me_action = '', me_action2 = '' where me_id = 637;
update sysmenu set me_action = '', me_action2 = '' where me_id = 746;
update sysmenu set me_action = '', me_action2 = '' where me_id = 764;
update sysmenu set me_action = '', me_action2 = '' where me_id = 879;
update sysmenu set me_action = '', me_action2 = '' where me_id = 800;
update sysmenu set me_action = '', me_action2 = '' where me_id = 802;
update sysmenu set me_action = '', me_action2 = '' where me_id = 838;
update sysmenu set me_action = '', me_action2 = '' where me_id = 841;
update sysmenu set me_action = '', me_action2 = '' where me_id = 856;
update sysmenu set me_action = '', me_action2 = '' where me_id = 872;
update sysmenu set me_action = '', me_action2 = '' where me_id = 876;
update sysmenu set me_action = '', me_action2 = '' where me_id = 885;
update sysmenu set me_action = '', me_action2 = '' where me_id = 897;
update sysmenu set me_action = '', me_action2 = '' where me_id = 898;
update sysmenu set me_action = '', me_action2 = '' where me_id = 899;
update sysmenu set me_action = '', me_action2 = '' where me_id = 901;
update sysmenu set me_action = '', me_action2 = '' where me_id = 902;
update sysmenu set me_action = '', me_action2 = '' where me_id = 904;
update sysmenu set me_action = '', me_action2 = '' where me_id = 906;
update sysmenu set me_action = '', me_action2 = '' where me_id = 881;
update sysmenu set me_action = '', me_action2 = '' where me_id = 888;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 778;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 758;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 501;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 469;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 496;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 864;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 868;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 532;
update sysmenu set me_action = 'show', me_action2 = '' where me_id = 548;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 677;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 851;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 556;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 566;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 622;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 624;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 635;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 706;
update sysmenu set me_action = '', me_action2 = '' where me_id = 927;
update sysmenu set me_action = '', me_action2 = '' where me_id = 468;
update sysmenu set me_action = '', me_action2 = '' where me_id = 480;
update sysmenu set me_action = '', me_action2 = '' where me_id = 495;
update sysmenu set me_action = '', me_action2 = '' where me_id = 543;
update sysmenu set me_action = '', me_action2 = '' where me_id = 478;
update sysmenu set me_action = '', me_action2 = '' where me_id = 482;
update sysmenu set me_action = '', me_action2 = '' where me_id = 484;
update sysmenu set me_action = '', me_action2 = '' where me_id = 506;
update sysmenu set me_action = '', me_action2 = '' where me_id = 569;
update sysmenu set me_action = '', me_action2 = '' where me_id = 592;
update sysmenu set me_action = '', me_action2 = '' where me_id = 619;
update sysmenu set me_action = '', me_action2 = '' where me_id = 485;
update sysmenu set me_action = '', me_action2 = '' where me_id = 486;
update sysmenu set me_action = '', me_action2 = '' where me_id = 487;
update sysmenu set me_action = '', me_action2 = '' where me_id = 497;
update sysmenu set me_action = '', me_action2 = '' where me_id = 544;
update sysmenu set me_action = '', me_action2 = '' where me_id = 546;
update sysmenu set me_action = '', me_action2 = '' where me_id = 759;
update sysmenu set me_action = '', me_action2 = '' where me_id = 775;
update sysmenu set me_action = '', me_action2 = '' where me_id = 799;
update sysmenu set me_action = '', me_action2 = '' where me_id = 834;
update sysmenu set me_action = '', me_action2 = '' where me_id = 836;
update sysmenu set me_action = '', me_action2 = '' where me_id = 839;
update sysmenu set me_action = '', me_action2 = '' where me_id = 846;
update sysmenu set me_action = '', me_action2 = '' where me_id = 850;
update sysmenu set me_action = '', me_action2 = '' where me_id = 854;
update sysmenu set me_action = '', me_action2 = '' where me_id = 859;
update sysmenu set me_action = '', me_action2 = '' where me_id = 887;
update sysmenu set me_action = '', me_action2 = '' where me_id = 892;
update sysmenu set me_action = '', me_action2 = '' where me_id = 848;
update sysmenu set me_action = '', me_action2 = '' where me_id = 861;
update sysmenu set me_action = '', me_action2 = '' where me_id = 863;
update sysmenu set me_action = '', me_action2 = '' where me_id = 867;
update sysmenu set me_action = '', me_action2 = '' where me_id = 869;
update sysmenu set me_action = '', me_action2 = '' where me_id = 883;
update sysmenu set me_action = '', me_action2 = '' where me_id = 555;
update sysmenu set me_action = '', me_action2 = '' where me_id = 831;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 826;
update sysmenu set me_action = '', me_action2 = '' where me_id = 488;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 776;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 740;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 745;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 801;
update sysmenu set me_action = '', me_action2 = '' where me_id = 545;
update sysmenu set me_action = '', me_action2 = '' where me_id = 559;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 700;
update sysmenu set me_action = '', me_action2 = '' where me_id = 575;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 908;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 560;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 774;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 828;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 830;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 837;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 840;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 855;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 770;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 772;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 766;
update sysmenu set me_action = '', me_action2 = '' where me_id = 682;
update sysmenu set me_action = '', me_action2 = '' where me_id = 641;
update sysmenu set me_action = '', me_action2 = '' where me_id = 701;
update sysmenu set me_action = '', me_action2 = '' where me_id = 656;
update sysmenu set me_action = '', me_action2 = '' where me_id = 672;
update sysmenu set me_action = '', me_action2 = '' where me_id = 741;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 790;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 882;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 862;
update sysmenu set me_action = 'import', me_action2 = '' where me_id = 866;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 871;
update sysmenu set me_action = '', me_action2 = '' where me_id = 636;
update sysmenu set me_action = '', me_action2 = '' where me_id = 640;
update sysmenu set me_action = '', me_action2 = '' where me_id = 638;
update sysmenu set me_action = 'validate', me_action2 = '' where me_id = 698;
update sysmenu set me_action = '', me_action2 = '' where me_id = 678;
update sysmenu set me_action = '', me_action2 = '' where me_id = 680;
update sysmenu set me_action = '', me_action2 = '' where me_id = 894;
update sysmenu set me_action = '', me_action2 = '' where me_id = 905;
update sysmenu set me_action = '', me_action2 = '' where me_id = 896;
update sysmenu set me_action = '', me_action2 = '' where me_id = 923;
update sysmenu set me_action = '', me_action2 = '' where me_id = 925;
update sysmenu set me_action = '', me_action2 = '' where me_id = 900;
update sysmenu set me_action = '', me_action2 = '' where me_id = 921;
update sysmenu set me_action = '', me_action2 = '' where me_id = 471;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 910;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 914;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 753;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 754;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 513;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 602;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 605;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 612;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 860;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 870;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 893;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 599;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 540;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 691;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 693;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 610;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 616;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 628;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 630;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 632;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 634;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 639;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 665;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 667;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 608;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 614;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 618;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 620;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 626;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 687;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 724;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 696;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 697;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 708;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 710;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 712;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 714;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 716;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 720;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 726;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 804;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 812;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 814;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 473;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 538;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 550;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 517;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 519;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 521;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 526;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 528;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 530;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 536;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 685;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 736;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 523;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 768;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 642;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 702;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 470;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 818;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 822;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 824;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 847;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 475;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 738;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 849;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 924;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 922;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 704;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 552;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 747;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 732;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 743;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 669;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 718;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 722;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 728;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 808;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 810;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 806;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 816;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 820;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 477;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 479;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 481;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 916;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 918;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 490;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 494;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 511;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 483;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 503;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 833;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 835;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 843;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 853;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 534;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 657;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 542;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 499;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 580;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 476;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 562;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 564;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 570;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 464;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 568;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 797;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 798;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 749;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 554;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 558;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 574;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 576;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 578;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 582;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 572;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 675;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 694;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 671;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 673;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 681;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 683;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 780;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 730;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 756;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 760;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 679;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 762;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 751;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 507;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 584;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 587;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 589;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 591;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 593;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 596;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 782;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 788;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 884;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 886;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 889;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 792;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 794;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 796;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 858;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 734;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 895;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 926;
update sysmenu set me_action = 'edit', me_action2 = '' where me_id = 786;

update sysmenu set me_action = 'show', me_action2 = '' where me_id = 784;
update sysmenu set me_action = 'show', me_action2 = '' where me_id = 699;
update sysmenu set me_action = 'list', me_action2 = 'edit' where me_id = 700;

update sysmenu set me_path = 'general/listaspreciomarcado', me_path2 = 'general/listapreciomarcado/:id' where me_id = 689;
update sysmenu set me_path = '', me_path2 = '' where me_id = 692;
update sysmenu set me_path = '', me_path2 = '' where me_id = 825;
update sysmenu set me_path = '', me_path2 = '' where me_id = 637;
update sysmenu set me_path = '', me_path2 = '' where me_id = 746;
update sysmenu set me_path = '', me_path2 = '' where me_id = 764;
update sysmenu set me_path = '', me_path2 = '' where me_id = 879;
update sysmenu set me_path = '', me_path2 = '' where me_id = 800;
update sysmenu set me_path = '', me_path2 = '' where me_id = 802;
update sysmenu set me_path = '', me_path2 = '' where me_id = 838;
update sysmenu set me_path = '', me_path2 = '' where me_id = 841;
update sysmenu set me_path = '', me_path2 = '' where me_id = 856;
update sysmenu set me_path = '', me_path2 = '' where me_id = 872;
update sysmenu set me_path = '', me_path2 = '' where me_id = 876;
update sysmenu set me_path = '', me_path2 = '' where me_id = 885;
update sysmenu set me_path = '', me_path2 = '' where me_id = 897;
update sysmenu set me_path = '', me_path2 = '' where me_id = 898;
update sysmenu set me_path = '', me_path2 = '' where me_id = 899;
update sysmenu set me_path = '', me_path2 = '' where me_id = 901;
update sysmenu set me_path = '', me_path2 = '' where me_id = 902;
update sysmenu set me_path = '', me_path2 = '' where me_id = 904;
update sysmenu set me_path = '', me_path2 = '' where me_id = 906;
update sysmenu set me_path = '', me_path2 = '' where me_id = 881;
update sysmenu set me_path = '', me_path2 = '' where me_id = 888;
update sysmenu set me_path = 'venta/importremito', me_path2 = '' where me_id = 778;
update sysmenu set me_path = 'venta/facturaventaanular', me_path2 = '' where me_id = 758;
update sysmenu set me_path = 'export/importaciontemporal', me_path2 = '' where me_id = 501;
update sysmenu set me_path = 'envio/envioconfig', me_path2 = '' where me_id = 469;
update sysmenu set me_path = 'export/exportconfig', me_path2 = '' where me_id = 496;
update sysmenu set me_path = 'implementacion/importacion', me_path2 = '' where me_id = 864;
update sysmenu set me_path = 'import/importacionproceso', me_path2 = '' where me_id = 868;
update sysmenu set me_path = 'venta/cobranzamenu', me_path2 = '' where me_id = 532;
update sysmenu set me_path = 'cvxi/browser', me_path2 = '' where me_id = 548;
update sysmenu set me_path = 'contabilidad/asientosedit', me_path2 = '' where me_id = 677;
update sysmenu set me_path = 'general/usuarioconfig', me_path2 = '' where me_id = 851;
update sysmenu set me_path = 'cvxi/producto', me_path2 = '' where me_id = 556;
update sysmenu set me_path = 'documento/documentoimpresora', me_path2 = '' where me_id = 566;
update sysmenu set me_path = 'tesoreria/bancoconciliacion', me_path2 = '' where me_id = 622;
update sysmenu set me_path = 'tesoreria/cashflow', me_path2 = '' where me_id = 624;
update sysmenu set me_path = 'tesoreria/rechazocheque', me_path2 = '' where me_id = 635;
update sysmenu set me_path = 'general/ajusteinflacionindice', me_path2 = '' where me_id = 706;
update sysmenu set me_path = '', me_path2 = '' where me_id = 927;
update sysmenu set me_path = '', me_path2 = '' where me_id = 468;
update sysmenu set me_path = '', me_path2 = '' where me_id = 480;
update sysmenu set me_path = '', me_path2 = '' where me_id = 495;
update sysmenu set me_path = '', me_path2 = '' where me_id = 543;
update sysmenu set me_path = '', me_path2 = '' where me_id = 478;
update sysmenu set me_path = '', me_path2 = '' where me_id = 482;
update sysmenu set me_path = '', me_path2 = '' where me_id = 484;
update sysmenu set me_path = '', me_path2 = '' where me_id = 506;
update sysmenu set me_path = '', me_path2 = '' where me_id = 569;
update sysmenu set me_path = '', me_path2 = '' where me_id = 592;
update sysmenu set me_path = '', me_path2 = '' where me_id = 619;
update sysmenu set me_path = '', me_path2 = '' where me_id = 485;
update sysmenu set me_path = '', me_path2 = '' where me_id = 486;
update sysmenu set me_path = '', me_path2 = '' where me_id = 487;
update sysmenu set me_path = '', me_path2 = '' where me_id = 497;
update sysmenu set me_path = '', me_path2 = '' where me_id = 544;
update sysmenu set me_path = '', me_path2 = '' where me_id = 546;
update sysmenu set me_path = '', me_path2 = '' where me_id = 759;
update sysmenu set me_path = '', me_path2 = '' where me_id = 775;
update sysmenu set me_path = '', me_path2 = '' where me_id = 799;
update sysmenu set me_path = '', me_path2 = '' where me_id = 834;
update sysmenu set me_path = '', me_path2 = '' where me_id = 836;
update sysmenu set me_path = '', me_path2 = '' where me_id = 839;
update sysmenu set me_path = '', me_path2 = '' where me_id = 846;
update sysmenu set me_path = '', me_path2 = '' where me_id = 850;
update sysmenu set me_path = '', me_path2 = '' where me_id = 854;
update sysmenu set me_path = '', me_path2 = '' where me_id = 859;
update sysmenu set me_path = '', me_path2 = '' where me_id = 887;
update sysmenu set me_path = '', me_path2 = '' where me_id = 892;
update sysmenu set me_path = '', me_path2 = '' where me_id = 848;
update sysmenu set me_path = '', me_path2 = '' where me_id = 861;
update sysmenu set me_path = '', me_path2 = '' where me_id = 863;
update sysmenu set me_path = '', me_path2 = '' where me_id = 867;
update sysmenu set me_path = '', me_path2 = '' where me_id = 869;
update sysmenu set me_path = '', me_path2 = '' where me_id = 883;
update sysmenu set me_path = '', me_path2 = '' where me_id = 555;
update sysmenu set me_path = '', me_path2 = '' where me_id = 831;
update sysmenu set me_path = 'compra/saldoinicial', me_path2 = '' where me_id = 826;
update sysmenu set me_path = '', me_path2 = '' where me_id = 488;
update sysmenu set me_path = 'contabilidad/importpercretiibb', me_path2 = '' where me_id = 776;
update sysmenu set me_path = 'compra/compraconfig', me_path2 = '' where me_id = 740;
update sysmenu set me_path = 'contabilidad/contconfig', me_path2 = '' where me_id = 745;
update sysmenu set me_path = 'personal/personalconfig', me_path2 = '' where me_id = 801;
update sysmenu set me_path = '', me_path2 = '' where me_id = 545;
update sysmenu set me_path = '', me_path2 = '' where me_id = 559;
update sysmenu set me_path = 'informe/informeconfig', me_path2 = '' where me_id = 700;
update sysmenu set me_path = '', me_path2 = '' where me_id = 575;
update sysmenu set me_path = 'tarea/agendas', me_path2 = 'tarea/agenda/:id' where me_id = 908;
update sysmenu set me_path = 'cvxi/textos', me_path2 = 'cvxi/texto/:id' where me_id = 560;
update sysmenu set me_path = 'contabilidad/importpadronembargo', me_path2 = '' where me_id = 774;
update sysmenu set me_path = 'venta/saldoinicial', me_path2 = '' where me_id = 828;
update sysmenu set me_path = 'stock/stockconfig', me_path2 = '' where me_id = 830;
update sysmenu set me_path = 'tesoreria/tesoreriaconfig', me_path2 = '' where me_id = 837;
update sysmenu set me_path = 'venta/ticketconfig', me_path2 = '' where me_id = 840;
update sysmenu set me_path = 'venta/ventaconfig', me_path2 = '' where me_id = 855;
update sysmenu set me_path = 'contabilidad/importasiento', me_path2 = '' where me_id = 770;
update sysmenu set me_path = 'venta/importordenservicio', me_path2 = '' where me_id = 772;
update sysmenu set me_path = 'general/generalconfig', me_path2 = '' where me_id = 766;
update sysmenu set me_path = '', me_path2 = '' where me_id = 682;
update sysmenu set me_path = '', me_path2 = '' where me_id = 641;
update sysmenu set me_path = '', me_path2 = '' where me_id = 701;
update sysmenu set me_path = '', me_path2 = '' where me_id = 656;
update sysmenu set me_path = '', me_path2 = '' where me_id = 672;
update sysmenu set me_path = '', me_path2 = '' where me_id = 741;
update sysmenu set me_path = 'tesoreria/monedas', me_path2 = 'tesoreria/moneda/:id' where me_id = 790;
update sysmenu set me_path = 'sistema/roles', me_path2 = 'sistema/rol/:id' where me_id = 882;
update sysmenu set me_path = 'impsql/edittables', me_path2 = '' where me_id = 862;
update sysmenu set me_path = 'import/import', me_path2 = '' where me_id = 866;
update sysmenu set me_path = 'infoafip/afipesquema', me_path2 = '' where me_id = 871;
update sysmenu set me_path = '', me_path2 = '' where me_id = 636;
update sysmenu set me_path = '', me_path2 = '' where me_id = 640;
update sysmenu set me_path = '', me_path2 = '' where me_id = 638;
update sysmenu set me_path = 'informe/validar', me_path2 = '' where me_id = 698;
update sysmenu set me_path = '', me_path2 = '' where me_id = 678;
update sysmenu set me_path = '', me_path2 = '' where me_id = 680;
update sysmenu set me_path = '', me_path2 = '' where me_id = 894;
update sysmenu set me_path = '', me_path2 = '' where me_id = 905;
update sysmenu set me_path = '', me_path2 = '' where me_id = 896;
update sysmenu set me_path = '', me_path2 = '' where me_id = 923;
update sysmenu set me_path = '', me_path2 = '' where me_id = 925;
update sysmenu set me_path = '', me_path2 = '' where me_id = 900;
update sysmenu set me_path = '', me_path2 = '' where me_id = 921;
update sysmenu set me_path = '', me_path2 = '' where me_id = 471;
update sysmenu set me_path = 'tarea/contactos', me_path2 = 'tarea/contacto/:id' where me_id = 910;
update sysmenu set me_path = 'tarea/horas', me_path2 = 'tarea/hora/:id' where me_id = 914;
update sysmenu set me_path = 'general/embalajes', me_path2 = 'general/embalaje/:id' where me_id = 753;
update sysmenu set me_path = 'general/empresas', me_path2 = 'general/empresa/:id' where me_id = 754;
update sysmenu set me_path = 'ticket/alarmaitemtipos', me_path2 = 'ticket/alarmaitemtipo/:id' where me_id = 513;
update sysmenu set me_path = 'personal/liquidacionplantillas', me_path2 = 'personal/liquidacionplantilla/:id' where me_id = 602;
update sysmenu set me_path = 'personal/sindicatos', me_path2 = 'personal/sindicato/:id' where me_id = 605;
update sysmenu set me_path = 'stock/partesdeprodkit', me_path2 = 'stock/parteprodkit/:id' where me_id = 612;
update sysmenu set me_path = 'general/zonas', me_path2 = 'general/zona/:id' where me_id = 860;
update sysmenu set me_path = 'infoafip/afipesquemas', me_path2 = 'infoafip/afipesquema/:id' where me_id = 870;
update sysmenu set me_path = 'produccion/maquinas', me_path2 = 'produccion/maquina/:id' where me_id = 893;
update sysmenu set me_path = 'personal/liquidacionformulas', me_path2 = 'personal/liquidacionformula/:id' where me_id = 599;
update sysmenu set me_path = 'venta/presupuestosdeventa', me_path2 = 'venta/presupuestodeventa/:id' where me_id = 540;
update sysmenu set me_path = 'general/marcas', me_path2 = 'general/marca/:id' where me_id = 691;
update sysmenu set me_path = 'general/stocklotes', me_path2 = 'general/stocklote/:id' where me_id = 693;
update sysmenu set me_path = 'stock/ordenesprodkit', me_path2 = 'stock/ordenprodkit/:id' where me_id = 610;
update sysmenu set me_path = 'stock/stocks', me_path2 = 'stock/stock/:id' where me_id = 616;
update sysmenu set me_path = 'tesoreria/despositosbanco', me_path2 = 'tesoreria/despositobanco/:id' where me_id = 628;
update sysmenu set me_path = 'tesoreria/depositosdecupon', me_path2 = 'tesoreria/depositoscupon/:id' where me_id = 630;
update sysmenu set me_path = 'tesoreria/movimientosfondo', me_path2 = 'tesoreria/movimientofondo/:id' where me_id = 632;
update sysmenu set me_path = 'tesoreria/ordenesdepago', me_path2 = 'tesoreria/ordendepago/:id' where me_id = 634;
update sysmenu set me_path = 'tesoreria/resolucionesdecupon', me_path2 = 'tesoreria/resoluciondecupon/:id' where me_id = 639;
update sysmenu set me_path = 'compra/despachosimpcalculos', me_path2 = 'compra/despachoimpcalculo/:id' where me_id = 665;
update sysmenu set me_path = 'compra/facturasdecompra', me_path2 = 'compra/facturadecompra/:id' where me_id = 667;
update sysmenu set me_path = 'personal/sindicatoconvenios', me_path2 = 'personal/sindicatoconvenio/:id' where me_id = 608;
update sysmenu set me_path = 'stock/recuentosdestock', me_path2 = 'stock/recuentostock/:id' where me_id = 614;
update sysmenu set me_path = 'stock/stockclientes', me_path2 = 'stock/stockcliente/:id' where me_id = 618;
update sysmenu set me_path = 'stock/stockproveedores', me_path2 = 'stock/stockproveedore/:id' where me_id = 620;
update sysmenu set me_path = 'tesoreria/cobranzas', me_path2 = 'tesoreria/cobranza/:id' where me_id = 626;
update sysmenu set me_path = 'general/cuentagrupos', me_path2 = 'general/cuentagrupo/:id' where me_id = 687;
update sysmenu set me_path = 'general/chequeras', me_path2 = 'general/chequera/:id' where me_id = 724;
update sysmenu set me_path = 'general/tarifarios', me_path2 = 'general/tarifario/:id' where me_id = 696;
update sysmenu set me_path = 'informe/informes', me_path2 = 'informe/informe/:id' where me_id = 697;
update sysmenu set me_path = 'general/bancos', me_path2 = 'general/banco/:id' where me_id = 708;
update sysmenu set me_path = 'general/cajas', me_path2 = 'general/caja/:id' where me_id = 710;
update sysmenu set me_path = 'general/calidades', me_path2 = 'general/calidade/:id' where me_id = 712;
update sysmenu set me_path = 'general/calles', me_path2 = 'general/calle/:id' where me_id = 714;
update sysmenu set me_path = 'general/camiones', me_path2 = 'general/camione/:id' where me_id = 716;
update sysmenu set me_path = 'general/catalogowebcategorias', me_path2 = 'general/catalogowebcategoria/:id' where me_id = 720;
update sysmenu set me_path = 'general/choferes', me_path2 = 'general/chofere/:id' where me_id = 726;
update sysmenu set me_path = 'general/posicionaranceles', me_path2 = 'general/posicionarancel/:id' where me_id = 804;
update sysmenu set me_path = 'general/proveedores', me_path2 = 'general/proveedor/:id' where me_id = 812;
update sysmenu set me_path = 'general/provincias', me_path2 = 'general/provincia/:id' where me_id = 814;
update sysmenu set me_path = 'empaque/puertos', me_path2 = 'empaque/puerto/:id' where me_id = 473;
update sysmenu set me_path = 'venta/pickinglists', me_path2 = 'venta/pickinglist/:id' where me_id = 538;
update sysmenu set me_path = 'cvxi/comunidadesinternet', me_path2 = 'cvxi/comunidadinternet/:id' where me_id = 550;
update sysmenu set me_path = 'ticket/equipos', me_path2 = 'ticket/equipo/:id' where me_id = 517;
update sysmenu set me_path = 'ticket/equipodetalles', me_path2 = 'ticket/equipodetalle/:id' where me_id = 519;
update sysmenu set me_path = 'ticket/equipotipofallas', me_path2 = 'ticket/equipotipofalla/:id' where me_id = 521;
update sysmenu set me_path = 'ticket/ordenservicios', me_path2 = 'ticket/ordenservicio/:id' where me_id = 526;
update sysmenu set me_path = 'ticket/partesdereparacion', me_path2 = 'ticket/partereparacion/:id' where me_id = 528;
update sysmenu set me_path = 'venta/cajas', me_path2 = 'venta/caja/:id' where me_id = 530;
update sysmenu set me_path = 'venta/hojasderutas', me_path2 = 'venta/hojaderuta/:id' where me_id = 536;
update sysmenu set me_path = 'general/cuentas', me_path2 = 'general/cuenta/:id' where me_id = 685;
update sysmenu set me_path = 'general/clientecontactotipos', me_path2 = 'general/clientecontactotipo/:id' where me_id = 736;
update sysmenu set me_path = 'ticket/emails', me_path2 = 'ticket/email/:id' where me_id = 523;
update sysmenu set me_path = 'general/idiomas', me_path2 = 'general/idioma/:id' where me_id = 768;
update sysmenu set me_path = 'alarmamail/alarmamails', me_path2 = 'alarmamail/alarmamail/:id' where me_id = 642;
update sysmenu set me_path = 'lenguaje/lenguajes', me_path2 = 'lenguaje/lenguaje/:id' where me_id = 702;
update sysmenu set me_path = 'empaque/contramarcas', me_path2 = 'empaque/contramarca/:id' where me_id = 470;
update sysmenu set me_path = 'general/retenciones', me_path2 = 'general/retencion/:id' where me_id = 818;
update sysmenu set me_path = 'general/rubros', me_path2 = 'general/rubro/:id' where me_id = 822;
update sysmenu set me_path = 'general/rubrotablas', me_path2 = 'general/rubrotabla/:id' where me_id = 824;
update sysmenu set me_path = 'general/transportes', me_path2 = 'general/transporte/:id' where me_id = 847;
update sysmenu set me_path = 'export/permisosdeembarque', me_path2 = 'export/permisodeembarque/:id' where me_id = 475;
update sysmenu set me_path = 'general/cobradores', me_path2 = 'general/cobrador/:id' where me_id = 738;
update sysmenu set me_path = 'general/unidades', me_path2 = 'general/unidad/:id' where me_id = 849;
update sysmenu set me_path = 'tarea/tareaplantillas', me_path2 = 'tarea/tareaplantilla/:id' where me_id = 924;
update sysmenu set me_path = 'tarea/tareas', me_path2 = 'tarea/tarea/:id' where me_id = 922;
update sysmenu set me_path = 'general/ajustesporinflacion', me_path2 = 'general/ajusteporinflacion/:id' where me_id = 704;
update sysmenu set me_path = 'cvxi/emails', me_path2 = 'cvxi/email/:id' where me_id = 552;
update sysmenu set me_path = 'general/departamentos', me_path2 = 'general/departamento/:id' where me_id = 747;
update sysmenu set me_path = 'general/clearings', me_path2 = 'general/clearing/:id' where me_id = 732;
update sysmenu set me_path = 'general/condicionesdepago', me_path2 = 'general/condiciondepago/:id' where me_id = 743;
update sysmenu set me_path = 'compra/ordenesdecompra', me_path2 = 'compra/ordendecompra/:id' where me_id = 669;
update sysmenu set me_path = 'general/catalogosweb', me_path2 = 'general/catalogoweb/:id' where me_id = 718;
update sysmenu set me_path = 'general/centrosdecosto', me_path2 = 'general/centrodecosto/:id' where me_id = 722;
update sysmenu set me_path = 'general/circuitoscontables', me_path2 = 'general/circuitocontable/:id' where me_id = 728;
update sysmenu set me_path = 'general/productoformulakits', me_path2 = 'general/productoformulakit/:id' where me_id = 808;
update sysmenu set me_path = 'general/productoshelpconfig', me_path2 = 'general/productohelpconfig/:id' where me_id = 810;
update sysmenu set me_path = 'general/productos', me_path2 = 'general/producto/:id' where me_id = 806;
update sysmenu set me_path = 'general/reglasliquidacion', me_path2 = 'general/reglaliquidacion/:id' where me_id = 816;
update sysmenu set me_path = 'general/retencionestipo', me_path2 = 'general/retenciontipo/:id' where me_id = 820;
update sysmenu set me_path = 'exportprint/expogrupoprecios', me_path2 = 'exportprint/expogrupoprecio/:id' where me_id = 477;
update sysmenu set me_path = 'envio/legajos', me_path2 = 'envio/legajo/:id' where me_id = 479;
update sysmenu set me_path = 'envio/legajotipos', me_path2 = 'envio/legajotipo/:id' where me_id = 481;
update sysmenu set me_path = 'tarea/prioridades', me_path2 = 'tarea/prioridad/:id' where me_id = 916;
update sysmenu set me_path = 'tarea/proyectos', me_path2 = 'tarea/proyecto/:id' where me_id = 918;
update sysmenu set me_path = 'export/aduanas', me_path2 = 'export/aduana/:id' where me_id = 490;
update sysmenu set me_path = 'export/embarques', me_path2 = 'export/embarque/:id' where me_id = 494;
update sysmenu set me_path = 'ticket/alarmas', me_path2 = 'ticket/alarma/:id' where me_id = 511;
update sysmenu set me_path = 'envio/partesdiarios', me_path2 = 'envio/partesdiario/:id' where me_id = 483;
update sysmenu set me_path = 'export/manifiestosdecarga', me_path2 = 'export/manifiestodecarga/:id' where me_id = 503;
update sysmenu set me_path = 'general/tarjetasdecredito', me_path2 = 'general/tarjetadecredito/:id' where me_id = 833;
update sysmenu set me_path = 'general/tasasimpositivas', me_path2 = 'general/tasaimpositiva/:id' where me_id = 835;
update sysmenu set me_path = 'general/tiposdeoperacion', me_path2 = 'general/tipodeoperacion/:id' where me_id = 843;
update sysmenu set me_path = 'general/vendedores', me_path2 = 'general/vendedor/:id' where me_id = 853;
update sysmenu set me_path = 'venta/facturasdeventa', me_path2 = 'venta/facturadeventa/:id' where me_id = 534;
update sysmenu set me_path = 'venta/pedidosdeventa', me_path2 = 'venta/pedidodeventa/:id' where me_id = 657;
update sysmenu set me_path = 'venta/remitosdeventa', me_path2 = 'venta/remitodeventa/:id' where me_id = 542;
update sysmenu set me_path = 'export/garantias', me_path2 = 'export/garantia/:id' where me_id = 499;
update sysmenu set me_path = 'edu/materias', me_path2 = 'edu/materia/:id' where me_id = 580;
update sysmenu set me_path = 'exportprint/expofamilias', me_path2 = 'exportprint/expofamilia/:id' where me_id = 476;
update sysmenu set me_path = 'documento/documentos', me_path2 = 'documento/documento/:id' where me_id = 562;
update sysmenu set me_path = 'documento/documentogrupos', me_path2 = 'documento/documentogrupo/:id' where me_id = 564;
update sysmenu set me_path = 'documento/talonarios', me_path2 = 'documento/talonario/:id' where me_id = 570;
update sysmenu set me_path = 'personal/empleadosarts', me_path2 = 'personal/empleadosart/:id' where me_id = 464;
update sysmenu set me_path = 'documento/fechasdecontroldeacceso', me_path2 = 'documento/fechadecontroldeacceso/:id' where me_id = 568;
update sysmenu set me_path = 'general/personas', me_path2 = 'general/persona/:id' where me_id = 797;
update sysmenu set me_path = 'general/personadocumentotipos', me_path2 = 'general/personadocumentotipo/:id' where me_id = 798;
update sysmenu set me_path = 'general/depositosficios', me_path2 = 'general/depositosficio/:id' where me_id = 749;
update sysmenu set me_path = 'cvxi/preguntas', me_path2 = 'cvxi/pregunta/:id' where me_id = 554;
update sysmenu set me_path = 'cvxi/respuestaplantillas', me_path2 = 'cvxi/respuestaplantilla/:id' where me_id = 558;
update sysmenu set me_path = 'empaque/calibradoras', me_path2 = 'empaque/calibradora/:id' where me_id = 574;
update sysmenu set me_path = 'empaque/configuracioncalibradoras', me_path2 = 'empaque/configuracioncalibradora/:id' where me_id = 576;
update sysmenu set me_path = 'edu/cursos', me_path2 = 'edu/curso/:id' where me_id = 578;
update sysmenu set me_path = 'edu/profesores', me_path2 = 'edu/profesor/:id' where me_id = 582;
update sysmenu set me_path = 'empaque/barcos', me_path2 = 'empaque/barco/:id' where me_id = 572;
update sysmenu set me_path = 'contabilidad/asientos', me_path2 = 'contabilidad/asiento/:id' where me_id = 675;
update sysmenu set me_path = 'general/sucursales', me_path2 = 'general/sucursal/:id' where me_id = 694;
update sysmenu set me_path = 'compra/pedidosdecompra', me_path2 = 'compra/pedidodecompra/:id' where me_id = 671;
update sysmenu set me_path = 'compra/remitosdecompra', me_path2 = 'compra/remitodecompra/:id' where me_id = 673;
update sysmenu set me_path = 'edu/alumnos', me_path2 = 'edu/alumno/:id' where me_id = 681;
update sysmenu set me_path = 'edu/aulas', me_path2 = 'edu/aula/:id' where me_id = 683;
update sysmenu set me_path = 'general/leyendas', me_path2 = 'general/leyenda/:id' where me_id = 780;
update sysmenu set me_path = 'general/ciudades', me_path2 = 'general/ciudade/:id' where me_id = 730;
update sysmenu set me_path = 'general/escalas', me_path2 = 'general/escala/:id' where me_id = 756;
update sysmenu set me_path = 'general/feriados', me_path2 = 'general/feriado/:id' where me_id = 760;
update sysmenu set me_path = 'contabilidad/ejercicioscontables', me_path2 = 'contabilidad/ejerciciocontable/:id' where me_id = 679;
update sysmenu set me_path = 'general/formasdepago', me_path2 = 'general/formadepago/:id' where me_id = 762;
update sysmenu set me_path = 'general/depositoslogicos', me_path2 = 'general/depositologico/:id' where me_id = 751;
update sysmenu set me_path = 'export/packinglists', me_path2 = 'export/packinglist/:id' where me_id = 507;
update sysmenu set me_path = 'personal/empleados', me_path2 = 'personal/empleado/:id' where me_id = 584;
update sysmenu set me_path = 'personal/empleadoasistenciatipos', me_path2 = 'personal/empleadoasistenciatipo/:id' where me_id = 587;
update sysmenu set me_path = 'personal/empleadoespecialidades', me_path2 = 'personal/empleadoespecialidad/:id' where me_id = 589;
update sysmenu set me_path = 'personal/empleadoperiodos', me_path2 = 'personal/empleadoperiodo/:id' where me_id = 591;
update sysmenu set me_path = 'personal/liquidaciones', me_path2 = 'personal/liquidacion/:id' where me_id = 593;
update sysmenu set me_path = 'personal/liquidacioncodigotipos', me_path2 = 'personal/liquidacioncodigotipo/:id' where me_id = 596;
update sysmenu set me_path = 'general/listasdedescuento', me_path2 = 'general/listadedescuento/:id' where me_id = 782;
update sysmenu set me_path = 'general/listasdeprecio', me_path2 = 'general/listadeprecio/:id' where me_id = 788;
update sysmenu set me_path = 'sistema/sysmodulos', me_path2 = 'sistema/sysmodulo/:id' where me_id = 884;
update sysmenu set me_path = 'sistema/tablas', me_path2 = 'sistema/tabla/:id' where me_id = 886;
update sysmenu set me_path = 'sistema/usuarios', me_path2 = 'sistema/usuario/:id' where me_id = 889;
update sysmenu set me_path = 'general/paises', me_path2 = 'general/pais/:id' where me_id = 792;
update sysmenu set me_path = 'general/percepciones', me_path2 = 'general/percepcion/:id' where me_id = 794;
update sysmenu set me_path = 'general/percepciontipos', me_path2 = 'general/percepciontipo/:id' where me_id = 796;
update sysmenu set me_path = 'general/ventamodos', me_path2 = 'general/ventamodo/:id' where me_id = 858;
update sysmenu set me_path = 'general/clientes', me_path2 = 'general/cliente/:id' where me_id = 734;
update sysmenu set me_path = 'produccion/productoboms', me_path2 = 'produccion/productobom/:id' where me_id = 895;
update sysmenu set me_path = 'tarea/tareaestados', me_path2 = 'tarea/tareaestado/:id' where me_id = 926;
update sysmenu set me_path = 'general/listaprecioconfig', me_path2 = '' where me_id = 786;
    
    update sysmenu set me_id_father = 848 where me_id = 689;

    update sysmenu set me_id_father = 927 where me_id = 825;
    update sysmenu set me_id_father = 638 where me_id = 637;
    update sysmenu set me_id_father = 834 where me_id = 746;
    update sysmenu set me_id_father = 836 where me_id = 764;
    update sysmenu set me_id_father = 888 where me_id = 879;
    update sysmenu set me_id_father = 799 where me_id = 800;
    update sysmenu set me_id_father = 800 where me_id = 802;
    update sysmenu set me_id_father = 836 where me_id = 838;
    update sysmenu set me_id_father = 925 where me_id = 841;
    update sysmenu set me_id_father = 859 where me_id = 856;
    update sysmenu set me_id_father = 869 where me_id = 872;
    update sysmenu set me_id_father = 881 where me_id = 876;
    update sysmenu set me_id_father = 883 where me_id = 885;
    update sysmenu set me_id_father = 896 where me_id = 897;
    update sysmenu set me_id_father = 896 where me_id = 898;
    update sysmenu set me_id_father = 896 where me_id = 899;
    update sysmenu set me_id_father = 900 where me_id = 901;
    update sysmenu set me_id_father = 900 where me_id = 902;
    update sysmenu set me_id_father = 905 where me_id = 904;
    update sysmenu set me_id_father = 905 where me_id = 906;
    update sysmenu set me_id_father = 887 where me_id = 881;
    update sysmenu set me_id_father = 887 where me_id = 888;
    update sysmenu set me_id_father = 859 where me_id = 778;
    update sysmenu set me_id_father = 859 where me_id = 758;
    update sysmenu set me_id_father = 506 where me_id = 501;
    update sysmenu set me_id_father = 484 where me_id = 469;
    update sysmenu set me_id_father = 495 where me_id = 496;
    update sysmenu set me_id_father = 863 where me_id = 864;
    update sysmenu set me_id_father = 867 where me_id = 868;
    update sysmenu set me_id_father = 656 where me_id = 532;
    update sysmenu set me_id_father = 555 where me_id = 548;
    update sysmenu set me_id_father = 678 where me_id = 677;
    update sysmenu set me_id_father = 850 where me_id = 851;
    update sysmenu set me_id_father = 555 where me_id = 556;
    update sysmenu set me_id_father = 569 where me_id = 566;
    update sysmenu set me_id_father = 638 where me_id = 622;
    update sysmenu set me_id_father = 638 where me_id = 624;
    update sysmenu set me_id_father = 638 where me_id = 635;
    update sysmenu set me_id_father = 834 where me_id = 706;

    update sysmenu set me_id_father = 927 where me_id = 468;
    update sysmenu set me_id_father = 927 where me_id = 480;
    update sysmenu set me_id_father = 927 where me_id = 495;
    update sysmenu set me_id_father = 927 where me_id = 543;




    update sysmenu set me_id_father = 927 where me_id = 569;


    update sysmenu set me_id_father = 484 where me_id = 485;
    update sysmenu set me_id_father = 480 where me_id = 486;
    update sysmenu set me_id_father = 480 where me_id = 487;
    update sysmenu set me_id_father = 495 where me_id = 497;
    update sysmenu set me_id_father = 545 where me_id = 544;
    update sysmenu set me_id_father = 545 where me_id = 546;
    update sysmenu set me_id_father = 927 where me_id = 759;
    update sysmenu set me_id_father = 927 where me_id = 775;
    update sysmenu set me_id_father = 927 where me_id = 799;
    update sysmenu set me_id_father = 927 where me_id = 834;
    update sysmenu set me_id_father = 927 where me_id = 836;
    update sysmenu set me_id_father = 927 where me_id = 839;
    update sysmenu set me_id_father = 927 where me_id = 846;
    update sysmenu set me_id_father = 927 where me_id = 850;
    update sysmenu set me_id_father = 927 where me_id = 854;
    update sysmenu set me_id_father = 927 where me_id = 859;
    update sysmenu set me_id_father = 927 where me_id = 887;
    update sysmenu set me_id_father = 927 where me_id = 892;
    update sysmenu set me_id_father = 927 where me_id = 848;






    update sysmenu set me_id_father = 846 where me_id = 831;
    update sysmenu set me_id_father = 825 where me_id = 826;
    update sysmenu set me_id_father = 480 where me_id = 488;
    update sysmenu set me_id_father = 834 where me_id = 776;
    update sysmenu set me_id_father = 825 where me_id = 740;
    update sysmenu set me_id_father = 834 where me_id = 745;
    update sysmenu set me_id_father = 800 where me_id = 801;

    update sysmenu set me_id_father = 927 where me_id = 559;
    update sysmenu set me_id_father = 699 where me_id = 700;
    update sysmenu set me_id_father = 927 where me_id = 575;
    update sysmenu set me_id_father = 925 where me_id = 908;
    update sysmenu set me_id_father = 559 where me_id = 560;
    update sysmenu set me_id_father = 834 where me_id = 774;
    update sysmenu set me_id_father = 859 where me_id = 828;
    update sysmenu set me_id_father = 846 where me_id = 830;
    update sysmenu set me_id_father = 836 where me_id = 837;
    update sysmenu set me_id_father = 925 where me_id = 840;
    update sysmenu set me_id_father = 859 where me_id = 855;
    update sysmenu set me_id_father = 834 where me_id = 770;
    update sysmenu set me_id_father = 859 where me_id = 772;
    update sysmenu set me_id_father = 850 where me_id = 766;
    update sysmenu set me_id_father = 927 where me_id = 682;

    update sysmenu set me_id_father = 927 where me_id = 701;


    update sysmenu set me_id_father = 825 where me_id = 741;
    update sysmenu set me_id_father = 836 where me_id = 790;
    update sysmenu set me_id_father = 881 where me_id = 882;
    update sysmenu set me_id_father = 863 where me_id = 862;
    update sysmenu set me_id_father = 867 where me_id = 866;
    update sysmenu set me_id_father = 869 where me_id = 871;

    update sysmenu set me_id_father = 927 where me_id = 640;

    update sysmenu set me_id_father = 883 where me_id = 698;


    update sysmenu set me_id_father = 927 where me_id = 894;
    update sysmenu set me_id_father = 927 where me_id = 905;

    update sysmenu set me_id_father = 927 where me_id = 923;
    update sysmenu set me_id_father = 927 where me_id = 925;


    update sysmenu set me_id_father = 575 where me_id = 471;
    update sysmenu set me_id_father = 925 where me_id = 910;
    update sysmenu set me_id_father = 923 where me_id = 914;
    update sysmenu set me_id_father = 848 where me_id = 753;
    update sysmenu set me_id_father = 887 where me_id = 754;
    update sysmenu set me_id_father = 925 where me_id = 513;
    update sysmenu set me_id_father = 800 where me_id = 602;
    update sysmenu set me_id_father = 800 where me_id = 605;
    update sysmenu set me_id_father = 619 where me_id = 612;
    update sysmenu set me_id_father = 859 where me_id = 860;
    update sysmenu set me_id_father = 869 where me_id = 870;
    update sysmenu set me_id_father = 894 where me_id = 893;
    update sysmenu set me_id_father = 800 where me_id = 599;
    update sysmenu set me_id_father = 656 where me_id = 540;
    update sysmenu set me_id_father = 848 where me_id = 691;
    update sysmenu set me_id_father = 692 where me_id = 693;
    update sysmenu set me_id_father = 619 where me_id = 610;
    update sysmenu set me_id_father = 619 where me_id = 616;
    update sysmenu set me_id_father = 638 where me_id = 628;
    update sysmenu set me_id_father = 638 where me_id = 630;
    update sysmenu set me_id_father = 638 where me_id = 632;
    update sysmenu set me_id_father = 638 where me_id = 634;
    update sysmenu set me_id_father = 638 where me_id = 639;
    update sysmenu set me_id_father = 672 where me_id = 665;
    update sysmenu set me_id_father = 672 where me_id = 667;
    update sysmenu set me_id_father = 800 where me_id = 608;
    update sysmenu set me_id_father = 619 where me_id = 614;
    update sysmenu set me_id_father = 619 where me_id = 618;
    update sysmenu set me_id_father = 619 where me_id = 620;
    update sysmenu set me_id_father = 638 where me_id = 626;
    update sysmenu set me_id_father = 834 where me_id = 687;
    update sysmenu set me_id_father = 836 where me_id = 724;
    update sysmenu set me_id_father = 859 where me_id = 696;
    update sysmenu set me_id_father = 883 where me_id = 697;
    update sysmenu set me_id_father = 836 where me_id = 708;
    update sysmenu set me_id_father = 836 where me_id = 710;
    update sysmenu set me_id_father = 848 where me_id = 712;
    update sysmenu set me_id_father = 850 where me_id = 714;
    update sysmenu set me_id_father = 846 where me_id = 716;
    update sysmenu set me_id_father = 848 where me_id = 720;
    update sysmenu set me_id_father = 846 where me_id = 726;
    update sysmenu set me_id_father = 848 where me_id = 804;
    update sysmenu set me_id_father = 825 where me_id = 812;
    update sysmenu set me_id_father = 850 where me_id = 814;
    update sysmenu set me_id_father = 575 where me_id = 473;
    update sysmenu set me_id_father = 656 where me_id = 538;
    update sysmenu set me_id_father = 559 where me_id = 550;
    update sysmenu set me_id_father = 923 where me_id = 517;
    update sysmenu set me_id_father = 925 where me_id = 519;
    update sysmenu set me_id_father = 925 where me_id = 521;
    update sysmenu set me_id_father = 923 where me_id = 526;
    update sysmenu set me_id_father = 923 where me_id = 528;
    update sysmenu set me_id_father = 656 where me_id = 530;
    update sysmenu set me_id_father = 656 where me_id = 536;
    update sysmenu set me_id_father = 834 where me_id = 685;
    update sysmenu set me_id_father = 859 where me_id = 736;
    update sysmenu set me_id_father = 925 where me_id = 523;
    update sysmenu set me_id_father = 850 where me_id = 768;
    update sysmenu set me_id_father = 883 where me_id = 642;

    update sysmenu set me_id_father = 575 where me_id = 470;
    update sysmenu set me_id_father = 834 where me_id = 818;
    update sysmenu set me_id_father = 848 where me_id = 822;
    update sysmenu set me_id_father = 848 where me_id = 824;
    update sysmenu set me_id_father = 846 where me_id = 847;
    update sysmenu set me_id_father = 506 where me_id = 475;
    update sysmenu set me_id_father = 859 where me_id = 738;
    update sysmenu set me_id_father = 848 where me_id = 849;
    update sysmenu set me_id_father = 923 where me_id = 924;
    update sysmenu set me_id_father = 923 where me_id = 922;
    update sysmenu set me_id_father = 834 where me_id = 704;
    update sysmenu set me_id_father = 555 where me_id = 552;
    update sysmenu set me_id_father = 887 where me_id = 747;
    update sysmenu set me_id_father = 836 where me_id = 732;
    update sysmenu set me_id_father = 836 where me_id = 743;
    update sysmenu set me_id_father = 672 where me_id = 669;
    update sysmenu set me_id_father = 848 where me_id = 718;
    update sysmenu set me_id_father = 834 where me_id = 722;
    update sysmenu set me_id_father = 834 where me_id = 728;
    update sysmenu set me_id_father = 848 where me_id = 808;
    update sysmenu set me_id_father = 848 where me_id = 810;
    update sysmenu set me_id_father = 848 where me_id = 806;
    update sysmenu set me_id_father = 859 where me_id = 816;
    update sysmenu set me_id_father = 834 where me_id = 820;
    update sysmenu set me_id_father = 495 where me_id = 477;
    update sysmenu set me_id_father = 480 where me_id = 479;
    update sysmenu set me_id_father = 480 where me_id = 481;
    update sysmenu set me_id_father = 925 where me_id = 916;
    update sysmenu set me_id_father = 925 where me_id = 918;
    update sysmenu set me_id_father = 495 where me_id = 490;
    update sysmenu set me_id_father = 506 where me_id = 494;
    update sysmenu set me_id_father = 925 where me_id = 511;
    update sysmenu set me_id_father = 482 where me_id = 483;
    update sysmenu set me_id_father = 506 where me_id = 503;
    update sysmenu set me_id_father = 836 where me_id = 833;
    update sysmenu set me_id_father = 834 where me_id = 835;
    update sysmenu set me_id_father = 859 where me_id = 843;
    update sysmenu set me_id_father = 859 where me_id = 853;
    update sysmenu set me_id_father = 656 where me_id = 534;
    update sysmenu set me_id_father = 656 where me_id = 657;
    update sysmenu set me_id_father = 656 where me_id = 542;
    update sysmenu set me_id_father = 506 where me_id = 499;
    update sysmenu set me_id_father = 682 where me_id = 580;
    update sysmenu set me_id_father = 495 where me_id = 476;
    update sysmenu set me_id_father = 569 where me_id = 562;
    update sysmenu set me_id_father = 569 where me_id = 564;
    update sysmenu set me_id_father = 569 where me_id = 570;
    update sysmenu set me_id_father = 800 where me_id = 464;
    update sysmenu set me_id_father = 569 where me_id = 568;
    update sysmenu set me_id_father = 887 where me_id = 797;
    update sysmenu set me_id_father = 887 where me_id = 798;
    update sysmenu set me_id_father = 846 where me_id = 749;
    update sysmenu set me_id_father = 555 where me_id = 554;
    update sysmenu set me_id_father = 559 where me_id = 558;
    update sysmenu set me_id_father = 575 where me_id = 574;
    update sysmenu set me_id_father = 575 where me_id = 576;
    update sysmenu set me_id_father = 680 where me_id = 578;
    update sysmenu set me_id_father = 682 where me_id = 582;
    update sysmenu set me_id_father = 575 where me_id = 572;
    update sysmenu set me_id_father = 678 where me_id = 675;
    update sysmenu set me_id_father = 887 where me_id = 694;
    update sysmenu set me_id_father = 672 where me_id = 671;
    update sysmenu set me_id_father = 672 where me_id = 673;
    update sysmenu set me_id_father = 680 where me_id = 681;
    update sysmenu set me_id_father = 682 where me_id = 683;
    update sysmenu set me_id_father = 834 where me_id = 780;
    update sysmenu set me_id_father = 850 where me_id = 730;
    update sysmenu set me_id_father = 848 where me_id = 756;
    update sysmenu set me_id_father = 836 where me_id = 760;
    update sysmenu set me_id_father = 678 where me_id = 679;
    update sysmenu set me_id_father = 836 where me_id = 762;
    update sysmenu set me_id_father = 846 where me_id = 751;
    update sysmenu set me_id_father = 506 where me_id = 507;
    update sysmenu set me_id_father = 799 where me_id = 584;
    update sysmenu set me_id_father = 799 where me_id = 587;
    update sysmenu set me_id_father = 799 where me_id = 589;
    update sysmenu set me_id_father = 592 where me_id = 591;
    update sysmenu set me_id_father = 592 where me_id = 593;
    update sysmenu set me_id_father = 800 where me_id = 596;
    update sysmenu set me_id_father = 848 where me_id = 782;
    update sysmenu set me_id_father = 848 where me_id = 788;
    update sysmenu set me_id_father = 883 where me_id = 884;
    update sysmenu set me_id_father = 883 where me_id = 886;
    update sysmenu set me_id_father = 888 where me_id = 889;
    update sysmenu set me_id_father = 850 where me_id = 792;
    update sysmenu set me_id_father = 834 where me_id = 794;
    update sysmenu set me_id_father = 834 where me_id = 796;
    update sysmenu set me_id_father = 859 where me_id = 858;
    update sysmenu set me_id_father = 859 where me_id = 734;
    update sysmenu set me_id_father = 894 where me_id = 895;
    update sysmenu set me_id_father = 925 where me_id = 926;
    update sysmenu set me_id_father = 848 where me_id = 786;

        update sysmenu set me_id_father = 848 where me_id = 784;
        update sysmenu set me_id_father = 848 where me_id = 702;
        update sysmenu set me_id_father = 848 where me_id = 699;
            
--insert into sysmenu (me_id, me_text, me_key, pre_id, me_father, me_position, me_is_last, me_is_separator, me_have_separator, me_is_main_menu, me_is_popup_menu, me_object_handler, me_package, me_file_path, me_id_father, me_action, me_path) values (927, '1028', 'csMenuConfig', null, '', 0, 1, 0, 1, 0, 0, '', 'CSGeneral', '', null, '', '');

update sysmenu set me_id_father = 656 where me_id = 555;
update sysmenu set me_id_father = 678 where me_id = 869;
    
update sysMenu set me_path = 'informe/config' where me_id = 699;
update sysMenu set me_path = 'general/calcularprecios' where me_id = 784;
                          

--insert into sysmenu (me_id, me_text, me_key, pre_id, me_father, me_position, me_is_last, me_is_separator, me_have_separator, me_is_main_menu, me_is_popup_menu, me_object_handler, me_package, me_file_path, me_id_father, me_action, me_path) values (928, '3701', 'csOtrosModulos', null, '', 0, 1, 0, 1, 0, 0, '', 'CSGeneral', '', null, '', '');

update sysmenu set me_id_father = 928 where me_id = 680;
update sysmenu set me_id_father = 928 where me_id = 863;
update sysmenu set me_id_father = 928 where me_id = 867;
update sysmenu set me_id_father = 928 where me_id = 923;
update sysmenu set me_id_father = 928 where me_id = 883;
update sysmenu set me_id_father = 928 where me_id = 506;
update sysmenu set me_id_father = 928 where me_id = 482;
update sysmenu set me_id_father = 928 where me_id = 619;
update sysmenu set me_id_father = 928 where me_id = 592;
update sysmenu set me_id_father = 619 where me_id = 693;

/*
   TODO: this class has to be translated using cProductoCVXI but in VB6 it is cProducto and it is in the CVXI folder
*/
update sysmenu set me_file_path = E'C:\\proyectos\\CSCVXI\\Codigo\\cairo\\cProductoCVXI.cls' where me_id = 555;
update sysmenu set me_object_handler = 'cProductoCVXI', me_action = 'edit', me_path = 'cvxi/productocvxi', me_file_path = E'C:\\proyectos\\CSCVXI\\Codigo\\cairo\\cProductoCVXI.cls' where me_id = 556;
update sysmodulo set sysm_objetoedicion = 'CSCVXI.cProductoCVXI' where sysm_id = 39015;


update sysMenu set me_action = 'edit', me_object_handler = 'cUsuarioPermiso', me_path = 'sistema/usuarios/permisos', me_action2 = '', me_path2 = '', pre_id = 8, me_father = 2758 where me_id = 879
update sysMenu set me_action = 'edit', me_object_handler = 'cRolPermiso', me_path = 'sistema/roles/permisos', me_action2 = '', me_path2 = '', pre_id = 8, me_father = 2756 where me_id = 876

update sysmodulo set sysm_objetoedicion = 'CSOAPIEdit.cUsuarioPermiso' where sysm_objetoedicion = 'CSOAPIEdit.cMenuPermisoUsuario'
update sysmodulo set sysm_objetoedicion = 'CSOAPIEdit.cRolPermiso' where sysm_objetoedicion = 'CSOAPIEdit.cMenuPermisoRol'

